#!/bin/bash
# Generates the GF Sandbox demo PKI and the mock Dezi signing key.
#
# Nothing this produces is committed: the output directory is gitignored. Run
# this once before
# `docker compose -f docker-compose.yml -f docker-compose.sandbox.yml --profile sandbox up`.
#
# A dedicated CA is generated rather than reusing test/e2e/pep/certs, which
# exists for PEP mTLS tests and issues UZI otherName certificates rather than
# TLS server certificates.
#
# Usage: ./sandbox/generate-demo-certs.sh

set -euo pipefail

# Keys land owner-only from the moment openssl creates them rather than after
# a later chmod. The final modes are set at the bottom, once it is clear which
# files a container has to read.
umask 077

OUT="$(cd "$(dirname "$0")" && pwd)/.certs"
mkdir -p "$OUT"

# The containers read these files as fixed non-root UIDs (18092 for mock-dezi,
# 18081 for the knooppunt), while a bind mount on Linux passes the host file's
# owner and mode straight through. Anything left at 0600 owned by the host user
# is therefore unreadable inside the container, and mock-dezi exits fatally on
# its signing key. Docker Desktop on macOS hides this by remapping the owner,
# which is why it only shows up on Linux and rootless Docker.
#
# So: certificates are public and get 0644, and the two keys the containers
# must read follow. Those two are throwaway material for a local demo,
# regenerated by deleting this directory, gitignored, and worthless outside
# this stack. The CA private key is the one thing no container mounts, so it
# stays owner-only.
#
# This runs on both paths, including the early exit below. An earlier version
# of this script left everything at 0600; someone who generated with it is
# exactly the person whose stack is broken, and re-running would otherwise
# tell them there is nothing to do while changing nothing.
#
# Every file is named rather than globbed. A glob over "$OUT" would sweep in
# whatever else happens to sit there: an unrelated private key called
# something.pem would be widened to 0644, and a dangling symlink would make
# chmod fail mid-command, which under `set -e` would abandon the rest of this
# function and leave the very outage it exists to repair.
#
# Directories are made searchable first, before anything tests for or changes a
# file inside them. An older run could leave $OUT or ca-only at 0700, and a
# directory that cannot be traversed makes every probe below it fail.
apply_modes() {
  chmod 755 "$OUT"
  if [[ -d $OUT/ca-only ]]; then
    chmod 755 "$OUT/ca-only"
  fi

  local name
  for name in ca.pem mock-dezi.pem mock-dezi.key dezi-signing.key; do
    if [[ -f $OUT/$name ]]; then
      chmod 644 "$OUT/$name"
    fi
  done
  if [[ -f $OUT/ca-only/gf-sandbox-demo-ca.pem ]]; then
    chmod 644 "$OUT/ca-only/gf-sandbox-demo-ca.pem"
  fi
  if [[ -f $OUT/ca.key ]]; then
    chmod 600 "$OUT/ca.key"
  fi
}

# Repair modes before probing for the material: a 0700 directory left by an
# older run would otherwise fail every -f test below and silently take the
# generation path, which then fails on the files that are already there.
apply_modes

if [[ -f $OUT/ca.pem && -f $OUT/ca.key && -f $OUT/mock-dezi.pem && -f $OUT/mock-dezi.key \
      && -f $OUT/dezi-signing.key && -f $OUT/ca-only/gf-sandbox-demo-ca.pem ]]; then
  echo "Demo material already present in $OUT; permissions normalized, nothing else to do."
  echo "Delete the directory and re-run to rotate it."
  exit 0
fi

echo "Generating demo CA..."
openssl genrsa -out "$OUT/ca.key" 4096
openssl req -x509 -new -nodes -key "$OUT/ca.key" -sha256 -days 3650 \
  -subj "/CN=GF Sandbox Demo CA/O=GF Sandbox" -out "$OUT/ca.pem"

echo "Generating mock-dezi server certificate..."
openssl genrsa -out "$OUT/mock-dezi.key" 2048
openssl req -new -key "$OUT/mock-dezi.key" -out "$OUT/mock-dezi.csr" \
  -subj "/CN=mock-dezi"

# Go ignores the Common Name for hostname verification, so the DNS SAN is
# mandatory, not decorative.
cat > "$OUT/mock-dezi.ext" <<'EOF'
extendedKeyUsage = serverAuth
subjectAltName = DNS:mock-dezi, DNS:localhost
EOF

#
# -CAserial is explicit rather than relying on -CAcreateserial's default
# naming: some OpenSSL/LibreSSL builds derive that default from the first
# dot in the full path, not the last dot in the basename, which turns the
# dotdir ".certs" into a stray sibling file (sandbox/.srl) outside $OUT.
openssl x509 -req -in "$OUT/mock-dezi.csr" -CA "$OUT/ca.pem" -CAkey "$OUT/ca.key" \
  -CAcreateserial -CAserial "$OUT/ca.srl" -out "$OUT/mock-dezi.pem" -days 3650 -sha256 \
  -extfile "$OUT/mock-dezi.ext"

echo "Generating mock Dezi attestation signing key..."
# mock-components/dezi/keys.go accepts either PKCS#1 or PKCS#8, but new keys
# are still written as PKCS#1 here for continuity with keys already deployed
# in that format. OpenSSL 3 defaults genrsa to PKCS#8; -traditional restores
# PKCS#1. LibreSSL, the macOS default, predates that flag and rejects it
# outright (nonzero exit, no file written), so probe for support first
# rather than letting the script fail under `set -e` on macOS.
if openssl genrsa -traditional -out /dev/null 512 >/dev/null 2>&1; then
  openssl genrsa -traditional -out "$OUT/dezi-signing.key" 2048
else
  openssl genrsa -out "$OUT/dezi-signing.key" 2048
fi

rm -f "$OUT/mock-dezi.csr" "$OUT/mock-dezi.ext"

# The containers read these files as fixed non-root UIDs (18092 for mock-dezi,
# 18081 for the knooppunt), while a bind mount on Linux passes the host file's
# owner and mode straight through. Anything left at 0600 owned by the host user
# is therefore unreadable inside the container, and mock-dezi exits fatally on
# its signing key. Docker Desktop on macOS hides this by remapping the owner,
# which is why it only shows up on Linux and rootless Docker.
# The knooppunt container mounts the file below into its certificate path.
# Keep private keys out of this directory: Go reads every file it finds in
# /etc/ssl/certs, and a future mount of the whole directory should not be able
# to pull one in.
mkdir -p "$OUT/ca-only"
cp "$OUT/ca.pem" "$OUT/ca-only/gf-sandbox-demo-ca.pem"

apply_modes

echo
echo "Written to $OUT (gitignored):"
echo "  ca.pem, ca.key             demo certificate authority"
echo "  mock-dezi.pem, .key        TLS server certificate, SAN mock-dezi + localhost"
echo "  dezi-signing.key           attestation signing key"
echo "  ca-only/                   CA alone, mounted into the knooppunt trust path"
