apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: nuts-knooppunt
servers: 1
agents: 0
volumes:
  - volume: ${PWD}/manifests:/var/lib/rancher/k3s/server/manifests/knpt
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6445"
image: rancher/k3s:v1.30.11-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - server:*
  - port: 443:443
    nodeFilters:
      - server:*
registries:
  create:
    name: knpt-registry.localhost
    host: "0.0.0.0"
    hostPort: "5005"
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
