apiVersion: v1
kind: Service
metadata:
  name: {{ include "gf-sandbox.fullname" . }}
  labels:
    {{- include "gf-sandbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.zonnebloemEhr.enabled }}
    - port: {{ .Values.zonnebloemEhr.port }}
      targetPort: zonnebloem-ehr
      protocol: TCP
      name: zonnebloem-ehr
    {{- end }}
  selector:
    {{- include "gf-sandbox.selectorLabels" . | nindent 4 }}
