{{- if .Values.fhir.enabled }}
apiVersion: postgresql.cnpg.io/v1 
kind: Cluster
metadata:
  name: {{ include "nuts-knooppunt.fullname" . }}-fhir-db
spec:
  instances: 1
  storage:
    size: 5Gi
{{- end }}
