/**
 * Dossierhoudende zorgaanbiedercategorieën (Dossier-holding healthcare provider categories)
 * Source: https://vzvz.atlassian.net/wiki/spaces/MA11/pages/828314634/Bijlage+Dossierhoudende+zorgaanbiedercategorie+n
 */
export const careOrganizationTypes = {
  "H1": "Huisartsinstelling",
  "K3": "Apotheekhoudende huisartspraktijk",
  "N6": "Huisartsenpost",
  "Z3": "Huisartsenpraktijk",
  "A1": "Apotheek",
  "J8": "Openbare apotheek",
  "K9": "Zelfstandig opererende ziekenhuisapotheek",
  "AMB": "Regionale ambulancevoorzieningen",
  "B3": "Radiotherapeutisch centrum",
  "BRA": "Brandwondencentrum",
  "DIA": "Dialysecentrum",
  "G3": "Verloskundepraktijk",
  "GC": "Geboortecentrum",
  "JZ": "Jeugdzorg",
  "P4": "Polikliniek (als onderdeel van een ziekenhuis)",
  "PM13": "Centrum voor eetstoornissen",
  "PM14": "Centrum voor orthopedie en beweging",
  "PM15": "Dermatologisch centrum",
  "R8": "Revalidatiecentrum",
  "SC": "Specialistisch Centrum",
  "TD": "Trombosedienst",
  "V4": "Ziekenhuis",
  "V5": "Universitair medisch centrum",
  "V6": "Algemeen ziekenhuis",
  "V7": "PUK / PAAZ afdeling ziekenhuis",
  "Z10": "Bloedbank",
  "Z12": "Cardiologiecentrum",
  "Z14": "Epilepsiekliniek",
  "Z15": "Esthetisch-medisch centrum",
  "Z16": "Flebologiecentrum",
  "Z17": "Forensisch centrum",
  "Z18": "Handcentrum en polscentrum",
  "Z19": "Kankercentrum",
  "Z20": "Oogkliniek",
  "Z21": "Pijncentrum",
  "Z22": "Psycho-oncologisch centrum",
  "Z23": "Sportmedisch centrum",
  "Z25": "IVF-kliniek",
  "Z26": "Transplantatie organisatie",
  "Z4": "Zelfstandig behandelcentrum",
  "Z6": "Abortuskliniek",
  "Z7": "Astmacentrum",
  "Z8": "Audiologisch centrum",
  "Z9": "Besnijdeniscentrum",
  "G6": "Verstandelijk gehandicaptenzorg",
  "H2": "Hospice",
  "IN10": "Woonvoorziening voor verstandelijk gehandicapten",
  "IN11": "Woonvoorziening voor visueel gehandicapten",
  "IN13": "Instelling voor verstandelijk gehandicapten",
  "IN15": "Zorg voor mensen met een beperking",
  "IN2": "Instelling voor auditief gehandicapten",
  "IN3": "Instelling voor lichamelijk gehandicapten",
  "IN5": "Instelling voor visueel gehandicapten",
  "IN7": "Verpleegkundig kinderdagverblijf",
  "IN9": "Woonvoorziening voor lichamelijk gehandicapten",
  "K4": "Kraamzorg",
  "M1": "Verzorgingstehuis",
  "R5": "Verpleeghuis",
  "T2": "Thuiszorg",
  "X3": "Verpleeghuis en verzorgingshuis",
  "B1": "Beeldvormende diagnostiek",
  "B2": "Echocentrum",
  "L1": "Laboratorium",
  "Z5": "Diagnostisch centrum",
  "G5": "Geestelijke gezondheidszorg (GGZ)",
  "G7": "Psychiatriepraktijk",
  "G8": "Psychologiepraktijk en psychotherapiepraktijk",
  "B4": "Bevolkingsonderzoek kanker",
  "C3": "Complementaire zorg",
  "F1": "Fysiotherapiepraktijk",
  "G1": "Verslavingszorg",
  "G9": "Gemeentelijke gezondheidsdienst",
  "JGZ": "Jeugdgezondheidszorg",
  "P6": "Preventieve gezondheidszorg",
  "PM10": "Orthoptistenpraktijk",
  "PM11": "Podologiepraktijk",
  "PM12": "Podotherapiepraktijk",
  "PM3": "Diëtistenpraktijk",
  "PM4": "Ergotherapiepraktijk",
  "PM6": "Huidtherapiepraktijk",
  "PM7": "Logopediepraktijk",
  "PM8": "Oefentherapiepraktijk",
  "PM9": "Optometriepraktijk",
  "TA1": "Tandartsinstelling",
  "TA2": "Tandartsenpraktijk",
  "TA3": "Centrum voor bijzondere tandheelkunde",
  "TA4": "Tandprothetische praktijk",
  "TA5": "Orthodontiepraktijk",
  "TA6": "Mondhygiënistenpraktijk",
  "Z27": "Pedicurepraktijk",
  "ZG": "Zorggroep"
} as const;

export type CareOrganizationType = keyof typeof careOrganizationTypes;

/**
 * Get organization type options as an array for use in dropdowns
 */
export function getOrganizationTypeOptions(): Array<{ code: CareOrganizationType; label: string }> {
  return Object.entries(careOrganizationTypes).map(([code, label]) => ({
    code: code as CareOrganizationType,
    label,
  }));
}

