version: '3.8'

services:
  dezi-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file: .env
    volumes:
      - ./cert.pem:/root/cert.pem:ro
      - ./cert-key.pem:/root/cert-key.pem:ro

