{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "fhir.fullname" . }}-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: {{ .Values.postgres.storage.size }}
{{- end }}
