### Proper registration at NVI via Bundle
POST http://localhost:8081/nvi
Content-Type: application/fhir+json

{
  "resourceType": "Bundle",
  "id": "nvi-org1",
  "entry": [
    {
      "request": {
        "method": "POST",
        "url": "List"
      },
      "resource": {
        "resourceType": "List",
        "extension": [
          {
            "valueReference": {
              "identifier": {
                "system": "http://fhir.nl/fhir/NamingSystem/ura",
                "value": "90000308"
              }
            },
            "url": "http://minvws.github.io/generiekefuncties-docs/StructureDefinition/nl-gf-localization-custodian"
          }
        ],
        "subject": {
          "identifier": {
            "system": "http://fhir.nl/fhir/NamingSystem/bsn",
            "value": "123456789"
          }
        },
        "source": {
          "identifier": {
            "system": "urn:ietf:rfc:3986",
            "value": "EHR-SYS-2024-999"
          },
          "type": "Device"
        },
        "status": "current",
        "mode": "working",
        "emptyReason": {
          "coding": [
            {
              "code": "withheld",
              "system": "http://terminology.hl7.org/CodeSystem/list-empty-reason"
            }
          ]
        },
        "code": {
          "coding": [
            {
              "code": "MEDAFSPRAAK",
              "system": "http://minvws.github.io/generiekefuncties-docs/CodeSystem/nl-gf-data-categories-cs",
              "display": "Medicatieafspraak"
            }
          ]
        }
      }
    }
  ],
  "type": "transaction"
}

### Proper registration at NVI
POST http://localhost:8081/nvi/List
Content-Type: application/fhir+json

{
  "resourceType": "List",
  "extension": [
    {
      "valueReference": {
        "identifier": {
          "system": "http://fhir.nl/fhir/NamingSystem/ura",
          "value": "90000308"
        }
      },
      "url": "http://minvws.github.io/generiekefuncties-docs/StructureDefinition/nl-gf-localization-custodian"
    }
  ],
  "subject": {
    "identifier": {
      "system": "http://fhir.nl/fhir/NamingSystem/bsn",
      "value": "123456789"
    }
  },
  "source": {
    "identifier": {
      "system": "urn:ietf:rfc:3986",
      "value": "EHR-SYS-2024-998"
    },
    "type": "Device"
  },
  "status": "current",
  "mode": "working",
  "emptyReason": {
    "coding": [
      {
        "code": "withheld",
        "system": "http://terminology.hl7.org/CodeSystem/list-empty-reason"
      }
    ]
  },
  "code": {
    "coding": [
      {
        "code": "MEDAFSPRAAK",
        "system": "http://minvws.github.io/generiekefuncties-docs/CodeSystem/nl-gf-data-categories-cs",
        "display": "Medicatieafspraak"
      }
    ]
  }
}

### NVI Search by patient
GET http://localhost:8081/nvi/List?patient:identifier=http://fhir.nl/fhir/NamingSystem/bsn|123456789
Accept: application/fhir+json

### NVI Search by patient and code
GET http://localhost:8081/nvi/List?patient:identifier=http://fhir.nl/fhir/NamingSystem/bsn|123456789&code=MEDAFSPRAAK
GET http://localhost:8081/nvi/List?patient:identifier=http://fhir.nl/fhir/NamingSystem/bsn|123456789&code=http://minvws.github.io/generiekefuncties-docs/CodeSystem/nl-gf-data-categories-cs|MEDAFSPRAAK
Accept: application/fhir+json

### NVI Search by patient and device
GET http://localhost:8081/nvi/List?patient:identifier=http://fhir.nl/fhir/NamingSystem/bsn|123456789&source:identifier=urn:ietf:rfc:3986|EHR-SYS-2024-999
Accept: application/fhir+json
