### Testing valid MCSD request

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
        "organization_ura": "00000666",
        "scope": "mcsd_update"
      }
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Organization/_history"
    },
    "context": {
      "data_holder_organization_id": "00000659",
      "connection_type_code": "hl7-fhir-rest"
    }
  }
}

### Testing search type request with valid parameter

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "organization_ura": "00000666",
      "scope": "mcsd_update"
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Organization",
      "query_params": {
        "_since": ["foo"]
      }
    },
    "context": {
      "data_holder_organization_id": "00000659",
      "connection_type_code": "hl7-fhir-rest"
    }
  }
}

### Testing request that leads to the "gesloten vraag"

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "user_id": "000095254",
      "user_role": "01.015",
      "organization_ura": "00000666",
      "organization_facility_type": "Z3",
      "scope": "bgz"
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Patient"
    },
    "context": {
      "data_holder_organization_id": "00000659",
      "data_holder_facility_type": "Z3",
      "connection_type_code": "hl7-fhir-rest"
    }
  }
}

### Testing request that parses a patient id
POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "user_id": "000095254",
      "user_role": "01.015",
      "organization_ura": "00000666",
      "organization_facility_type": "Z3",
      "scope": "bgz"
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Patient/3E439979-017F-40AA-594D-EBCF880FFD97"
    },
    "context": {
      "data_holder_organization_id": "00000659",
      "data_holder_facility_type": "Z3",
      "connection_type_code": "hl7-fhir-rest"
    }
  }
}

### Testing policy that does not have a capability statement 
POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "user_id": "000095254",
      "user_role": "01.015",
      "organization_ura": "00000666",
      "organization_facility_type": "Z3",
      "scope": "eoverdracht_notification"
    },
    "request": {
      "method": "POST",
      "protocol": "HTTP/1.0",
      "path": "/"
    },
    "context": {
      "data_holder_organization_id": "00000659",
      "data_holder_facility_type": "Z3",
      "connection_type_code": "hl7-fhir-rest"
    }
  }
}

### Testing pzp call
POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "user_id": "000095254",
      "user_role": "01.015",
      "organization_ura": "00000666",
      "organization_facility_type": "Z3",
      "scope": "pzp_gf"
    },
    "request": {
      "method": "POST",
      "protocol": "HTTP/1.0",
      "path": "/Patient/_search",
      "header": {
        "Content-Type": ["application/x-www-form-urlencoded"]
      },
      "body": "identifier=http://fhir.nl/fhir/NamingSystem/bsn|900214181"
    },
    "context": {
      "data_holder_organization_id": "90000697",
      "data_holder_facility_type": "Z3",
      "connection_type_code": "hl7-fhir-rest"
    }
  }
}

### Testing put on notification task
POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "user_id": "000095254",
      "user_role": "01.015",
      "organization_ura": "00000040",
      "organization_facility_type": "Z3",
      "scope": "eoverdracht-sender"
    },
    "request": {
      "method": "PUT",
      "protocol": "HTTP/1.0",
      "path": "/Task/B033BD18-60A0-4648-3219-AC2A7A27C049"
    },
    "context": {
      "data_holder_organization_id": "00000030",
      "data_holder_facility_type": "Z3",
      "connection_type_code": "hl7-fhir-rest"
    }
  }
}
