### Testing valid MCSD request

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "properties": {
        "subject_organization_id": "00000666",
        "client_qualifications": ["mcsd_update"]
      }
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Organization/_history"
    },
    "context": {
      "data_holder_organization_id": "00000659"
    }
  }
}

### Testing search type request with valid parameter

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "properties": {
        "subject_organization_id": "00000666",
        "client_qualifications": ["mcsd_update"]
      }
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Organization?",
      "query_params": {
        "_since": ["foo"]
      }
    },
    "context": {
      "data_holder_organization_id": "00000659"
    }
  }
}

### Testing "gesloten vraag" request

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "scope": "bgz_professional",
    "resource_id": "123445",
    "resource_type": "Patient",
    "patient_bsn": "900186021",
    "requesting_uzi_role_code": "01.015",
    "requesting_practitioner_identifier": "000095254",
    "requesting_organization_ura": "00000666",
    "requesting_facility_type": "Z3",
    "data_holder_organization_ura": "00000659",
    "data_holder_facility_type": "Z3",
    "purpose_of_use": "treatment"
  }
}

### Testing invalid request

POST http://localhost:8081/pdp
Content-Type: application/json

{
  "input": {
    "patient_bsn": "",
    "requesting_uzi_role_code": "true"
  }
}
