// Code generated by component/mcsdadmin/valuesets/codegen/main.go; DO NOT EDIT.

package valuesets

import "github.com/zorgbijjou/golang-fhir-models/fhir-models/fhir"

var EndpointConnectionTypeCodings []fhir.Coding
var EndpointPayloadTypeCodings []fhir.Coding
var EndpointStatusCodings []fhir.Coding
var LocationPhysicalTypeCodings []fhir.Coding
var LocationStatusCodings []fhir.Coding
var LocationTypeCodings []fhir.Coding
var OrganizationTypeCodings []fhir.Coding
var PurposeOfUseCodings []fhir.Coding
var ServiceTypeCodings []fhir.Coding

func init() {
	EndpointConnectionTypeCodings = getValueSets()["endpoint-connection-type"]
	if EndpointConnectionTypeCodings == nil {
		panic("Value set endpoint-connection-type.json not found")
	}
	EndpointPayloadTypeCodings = getValueSets()["endpoint-payload-type"]
	if EndpointPayloadTypeCodings == nil {
		panic("Value set endpoint-payload-type.json not found")
	}
	EndpointStatusCodings = getValueSets()["endpoint-status"]
	if EndpointStatusCodings == nil {
		panic("Value set endpoint-status.json not found")
	}
	LocationPhysicalTypeCodings = getValueSets()["location-physical-type"]
	if LocationPhysicalTypeCodings == nil {
		panic("Value set location-physical-type.json not found")
	}
	LocationStatusCodings = getValueSets()["location-status"]
	if LocationStatusCodings == nil {
		panic("Value set location-status.json not found")
	}
	LocationTypeCodings = getValueSets()["location-type"]
	if LocationTypeCodings == nil {
		panic("Value set location-type.json not found")
	}
	OrganizationTypeCodings = getValueSets()["organization-type"]
	if OrganizationTypeCodings == nil {
		panic("Value set organization-type.json not found")
	}
	PurposeOfUseCodings = getValueSets()["purpose-of-use"]
	if PurposeOfUseCodings == nil {
		panic("Value set purpose-of-use.json not found")
	}
	ServiceTypeCodings = getValueSets()["service-type"]
	if ServiceTypeCodings == nil {
		panic("Value set service-type.json not found")
	}
}
