// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=component_mock.go -package=mitz -source=interface.go
//

// Package mitz is a generated GoMock package.
package mitz

import (
	context "context"
	reflect "reflect"

	xacml "github.com/nuts-foundation/nuts-knooppunt/component/mitz/xacml"
	gomock "go.uber.org/mock/gomock"
)

// MockConsentChecker is a mock of ConsentChecker interface.
type MockConsentChecker struct {
	ctrl     *gomock.Controller
	recorder *MockConsentCheckerMockRecorder
	isgomock struct{}
}

// MockConsentCheckerMockRecorder is the mock recorder for MockConsentChecker.
type MockConsentCheckerMockRecorder struct {
	mock *MockConsentChecker
}

// NewMockConsentChecker creates a new mock instance.
func NewMockConsentChecker(ctrl *gomock.Controller) *MockConsentChecker {
	mock := &MockConsentChecker{ctrl: ctrl}
	mock.recorder = &MockConsentCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentChecker) EXPECT() *MockConsentCheckerMockRecorder {
	return m.recorder
}

// CheckConsent mocks base method.
func (m *MockConsentChecker) CheckConsent(ctx context.Context, authzReq xacml.AuthzRequest) (*xacml.XACMLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConsent", ctx, authzReq)
	ret0, _ := ret[0].(*xacml.XACMLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckConsent indicates an expected call of CheckConsent.
func (mr *MockConsentCheckerMockRecorder) CheckConsent(ctx, authzReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConsent", reflect.TypeOf((*MockConsentChecker)(nil).CheckConsent), ctx, authzReq)
}
