apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mock-prs.fullname" . }}-keys
  labels:
    {{- include "mock-prs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
