@startuml

title Dezi login and user identity in data exchanges

box "Local XIS"
    actor User
    participant Browser
    participant EHR
    participant Knooppunt
    participant AuthClient as "OAuth Client\n(Nuts Node)"
end box
participant Dezi
participant RemoteXIS as "Remote XIS"

== Dezi login\n  opt. A: EHR integrates with Dezi ==
User -> EHR : Login/Interact
activate EHR
EHR -> Browser : Make Auth Request,\nredirect
deactivate EHR
group Dezi OIDC Authorized Code Flow
Browser -> Dezi : OIDC Authorization Request\n(scope=openid profile)
activate Dezi
Dezi --> Browser : Request authentication
deactivate Dezi

User -> Browser : Login
Browser -> Dezi : User auth (e.g. DigiD)
activate Dezi
Dezi --> Browser : OIDC Auth Response\n(auth code)
deactivate Dezi
Browser -> EHR : Redirect\n(auth code)
activate EHR
EHR -> Dezi : OIDC Token Request\n(auth code)
activate Dezi
    Dezi --> EHR : OIDC Token Response\n(id_token(encrypted))
deactivate Dezi
group Dezi business rules
    EHR -> EHR : Process id_token(encrypted)
    activate EHR
    EHR -> EHR : Decrypt id_token(encrypted)
    EHR -> EHR : Validate id_token claims
    EHR -> Dezi : Get revocation status
    activate Dezi
    Dezi --> EHR : Revocation status
    deactivate Dezi
    EHR -> EHR : Check revocation status
    EHR --> EHR : OK/NOK
    deactivate EHR
end group
end group
EHR --> EHR : Store id_token or,\ncreate user session
EHR --> Browser : User logged in
deactivate EHR

== Dezi login\n  opt. B: Knooppunt as IDP,\n  Knooppunt integrates with Dezi ==
User -> EHR : Login/Interact
activate EHR
EHR -> Browser : Make Auth Request,\nredirect
deactivate EHR
Browser -> Knooppunt : OIDC Authorization Request\n(scope=openid profile)
activate Knooppunt
Knooppunt -> Knooppunt : Make redirect URL\nfor Dezi auth
Knooppunt --> Browser : redirect URL
deactivate Knooppunt
group Dezi OIDC Authorized Code Flow
Browser -> Dezi : OIDC Authorization Request\n(scope=openid profile)
activate Dezi
Dezi --> Browser : Request authentication
deactivate Dezi

User -> Browser : Login
Browser -> Dezi : User auth (e.g. DigiD)
activate Dezi
Dezi --> Browser : OIDC Auth Response\n(auth code)
deactivate Dezi
Browser -> Knooppunt : Redirect\n(auth code)
activate Knooppunt
Knooppunt -> Dezi : OIDC Token Request\n(auth code)
activate Dezi
    Dezi --> Knooppunt : OIDC Token Response\n(id_token(encrypted))
deactivate Dezi
group Dezi business rules
    Knooppunt -> Knooppunt : Process id_token(encrypted)
    activate Knooppunt
    Knooppunt -> Knooppunt : Decrypt id_token(encrypted)
    Knooppunt -> Knooppunt : Validate id_token claims
    Knooppunt -> Dezi : Get revocation status
    activate Dezi
    Dezi --> Knooppunt : Revocation status
    deactivate Dezi
    Knooppunt -> Knooppunt : Check revocation status
    Knooppunt --> Knooppunt : OK/NOK
    deactivate Knooppunt
end group
end group
Knooppunt --> Knooppunt : Store id_token in session
Knooppunt --> Browser : OIDC Auth Response\n(auth code)
deactivate Knooppunt
Browser -> EHR : Redirect\n(auth code)
activate EHR
EHR -> Knooppunt : OIDC Token Request\n(auth code)
activate Knooppunt
    Knooppunt -> Knooppunt : Create DeziIDTokenCredential\n(id_token)
    Knooppunt --> EHR : OIDC Token Response\n(id_token,\nDeziIDTokenCredential)
    note right : Custom field in token response:\nDeziIDTokenCredential
deactivate Knooppunt
EHR -> EHR : Update/create user session\n(id_token,\nDeziIDTokenCredential)
EHR --> Browser : User logged in
deactivate EHR

== Fetching data with user identity ==
User -> EHR : Request data\nfrom remote source
activate EHR
group Get access token
    group IF: EHR integrated directly with Dezi
    EHR -> Knooppunt : Create DeziIDTokenCredential\n(id_token)
    activate Knooppunt
    Knooppunt --> EHR : DeziIDTokenCredential
    deactivate Knooppunt
    end group
    EHR -> AuthClient : Request token\n(DeziIDTokenCredential)
    activate AuthClient
    AuthClient --> EHR : Token Response\n(access token)
    note right : Token is requested at\nremote OAuth server
    deactivate AuthClient
end

EHR -> RemoteXIS : Data request\n(access token)
activate RemoteXIS
RemoteXIS --> EHR : Data response\n(e.g. FHIR)
deactivate RemoteXIS
EHR --> User : Data response
deactivate EHR
@enduml