//go:build go1.22

// Package subscriptionpublic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package subscriptionpublic

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// BackportSubscription An R4 Subscription profiled per the Subscriptions R5 Backport IG: `_criteria` carries backport-topic-canonical and backport-filter-criteria, `channel._payload` carries backport-payload-content, `channel.extension` may carry backport-heartbeat-period. Not redefined here.
type BackportSubscription map[string]interface{}

// FHIRBundle A FHIR R4 Bundle; notification Bundles conform to backport-subscription-notification (type `history`). Not redefined here.
type FHIRBundle map[string]interface{}

// FHIROperationOutcome A FHIR R4 OperationOutcome resource, returned for error responses. Not redefined here.
type FHIROperationOutcome map[string]interface{}

// FHIRResource An arbitrary FHIR R4 resource, passed through verbatim. See https://hl7.org/fhir/R4/ for schemas; not redefined here.
type FHIRResource map[string]interface{}

// SubscriptionTopic An R4B/R5-format SubscriptionTopic served as a design-time artifact. Not redefined here.
type SubscriptionTopic map[string]interface{}

// SubscriptionID defines model for SubscriptionID.
type SubscriptionID = string

// OperationOutcomeError A FHIR R4 OperationOutcome resource, returned for error responses. Not redefined here.
type OperationOutcomeError = FHIROperationOutcome

// GetSubscriptionEventsParams defines parameters for GetSubscriptionEvents.
type GetSubscriptionEventsParams struct {
	// EventsSinceNumber First event number to replay (inclusive). Defaults to 1.
	EventsSinceNumber *int64 `form:"eventsSinceNumber,omitempty" json:"eventsSinceNumber,omitempty"`

	// EventsUntilNumber Last event number to replay (inclusive). Defaults to the latest.
	EventsUntilNumber *int64 `form:"eventsUntilNumber,omitempty" json:"eventsUntilNumber,omitempty"`
}

// CreateSubscriptionApplicationFhirPlusJSONRequestBody defines body for CreateSubscription for application/fhir+json ContentType.
type CreateSubscriptionApplicationFhirPlusJSONRequestBody = BackportSubscription

// ReceiveNotificationApplicationFhirPlusJSONRequestBody defines body for ReceiveNotification for application/fhir+json ContentType.
type ReceiveNotificationApplicationFhirPlusJSONRequestBody = FHIRBundle

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateSubscription Create a Subscription (in-band)
	// (POST /fhir/Subscription)
	CreateSubscription(w http.ResponseWriter, r *http.Request)
	// GetSubscription Read a Subscription
	// (GET /fhir/Subscription/{id})
	GetSubscription(w http.ResponseWriter, r *http.Request, id SubscriptionID)
	// GetSubscriptionEvents Replay events ($events)
	// (GET /fhir/Subscription/{id}/$events)
	GetSubscriptionEvents(w http.ResponseWriter, r *http.Request, id SubscriptionID, params GetSubscriptionEventsParams)
	// GetSubscriptionStatus Query subscription status ($status)
	// (GET /fhir/Subscription/{id}/$status)
	GetSubscriptionStatus(w http.ResponseWriter, r *http.Request, id SubscriptionID)
	// GetSubscriptionTopic Read an agreed SubscriptionTopic
	// (GET /fhir/SubscriptionTopic/{id})
	GetSubscriptionTopic(w http.ResponseWriter, r *http.Request, id string)
	// ReadAliasedTask Read a Task by its aliased (opaque) id
	// (GET /fhir/Task/{id})
	ReadAliasedTask(w http.ResponseWriter, r *http.Request, id string)
	// ReceiveNotification Receive a notification Bundle (rest-hook endpoint)
	// (POST /fhir/notifications)
	ReceiveNotification(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateSubscription operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscription(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscription operation middleware
func (siw *ServerInterfaceWrapper) GetSubscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SubscriptionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscription(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscriptionEvents operation middleware
func (siw *ServerInterfaceWrapper) GetSubscriptionEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SubscriptionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSubscriptionEventsParams

	// ------------- Optional query parameter "eventsSinceNumber" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "eventsSinceNumber", r.URL.Query(), &params.EventsSinceNumber, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "eventsSinceNumber"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventsSinceNumber", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "eventsUntilNumber" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "eventsUntilNumber", r.URL.Query(), &params.EventsUntilNumber, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "eventsUntilNumber"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventsUntilNumber", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscriptionEvents(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscriptionStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSubscriptionStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SubscriptionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscriptionStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubscriptionTopic operation middleware
func (siw *ServerInterfaceWrapper) GetSubscriptionTopic(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubscriptionTopic(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReadAliasedTask operation middleware
func (siw *ServerInterfaceWrapper) ReadAliasedTask(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReadAliasedTask(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveNotification operation middleware
func (siw *ServerInterfaceWrapper) ReceiveNotification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveNotification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/fhir/Subscription", wrapper.CreateSubscription)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/fhir/Subscription/{id}", wrapper.GetSubscription)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/fhir/Subscription/{id}/$status", wrapper.GetSubscriptionStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/fhir/Subscription/{id}/$events", wrapper.GetSubscriptionEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/fhir/SubscriptionTopic/{id}", wrapper.GetSubscriptionTopic)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/fhir/Task/{id}", wrapper.ReadAliasedTask)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/fhir/notifications", wrapper.ReceiveNotification)

	return m
}

type OperationOutcomeErrorApplicationFhirPlusJSONResponse FHIROperationOutcome

type CreateSubscriptionRequestObject struct {
	Body *CreateSubscriptionApplicationFhirPlusJSONRequestBody
}

type CreateSubscriptionResponseObject interface {
	VisitCreateSubscriptionResponse(w http.ResponseWriter) error
}

type CreateSubscription201ApplicationFhirPlusJSONResponse BackportSubscription

func (response CreateSubscription201ApplicationFhirPlusJSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubscription400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response CreateSubscription400ApplicationFhirPlusJSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubscription422ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response CreateSubscription422ApplicationFhirPlusJSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionRequestObject struct {
	Id SubscriptionID `json:"id"`
}

type GetSubscriptionResponseObject interface {
	VisitGetSubscriptionResponse(w http.ResponseWriter) error
}

type GetSubscription200ApplicationFhirPlusJSONResponse BackportSubscription

func (response GetSubscription200ApplicationFhirPlusJSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscription404ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response GetSubscription404ApplicationFhirPlusJSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionEventsRequestObject struct {
	Id     SubscriptionID `json:"id"`
	Params GetSubscriptionEventsParams
}

type GetSubscriptionEventsResponseObject interface {
	VisitGetSubscriptionEventsResponse(w http.ResponseWriter) error
}

type GetSubscriptionEvents200ApplicationFhirPlusJSONResponse FHIRBundle

func (response GetSubscriptionEvents200ApplicationFhirPlusJSONResponse) VisitGetSubscriptionEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionEvents404ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response GetSubscriptionEvents404ApplicationFhirPlusJSONResponse) VisitGetSubscriptionEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionEvents422ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response GetSubscriptionEvents422ApplicationFhirPlusJSONResponse) VisitGetSubscriptionEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionStatusRequestObject struct {
	Id SubscriptionID `json:"id"`
}

type GetSubscriptionStatusResponseObject interface {
	VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error
}

type GetSubscriptionStatus200ApplicationFhirPlusJSONResponse FHIRBundle

func (response GetSubscriptionStatus200ApplicationFhirPlusJSONResponse) VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionStatus404ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response GetSubscriptionStatus404ApplicationFhirPlusJSONResponse) VisitGetSubscriptionStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionTopicRequestObject struct {
	Id string `json:"id"`
}

type GetSubscriptionTopicResponseObject interface {
	VisitGetSubscriptionTopicResponse(w http.ResponseWriter) error
}

type GetSubscriptionTopic200ApplicationFhirPlusJSONResponse SubscriptionTopic

func (response GetSubscriptionTopic200ApplicationFhirPlusJSONResponse) VisitGetSubscriptionTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionTopic404ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response GetSubscriptionTopic404ApplicationFhirPlusJSONResponse) VisitGetSubscriptionTopicResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReadAliasedTaskRequestObject struct {
	Id string `json:"id"`
}

type ReadAliasedTaskResponseObject interface {
	VisitReadAliasedTaskResponse(w http.ResponseWriter) error
}

type ReadAliasedTask200ApplicationFhirPlusJSONResponse FHIRResource

func (response ReadAliasedTask200ApplicationFhirPlusJSONResponse) VisitReadAliasedTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReadAliasedTask404ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response ReadAliasedTask404ApplicationFhirPlusJSONResponse) VisitReadAliasedTaskResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveNotificationRequestObject struct {
	Body *ReceiveNotificationApplicationFhirPlusJSONRequestBody
}

type ReceiveNotificationResponseObject interface {
	VisitReceiveNotificationResponse(w http.ResponseWriter) error
}

type ReceiveNotification200Response struct {
}

func (response ReceiveNotification200Response) VisitReceiveNotificationResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type ReceiveNotification400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response ReceiveNotification400ApplicationFhirPlusJSONResponse) VisitReceiveNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveNotification422ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response ReceiveNotification422ApplicationFhirPlusJSONResponse) VisitReceiveNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateSubscription Create a Subscription (in-band)
	// (POST /fhir/Subscription)
	CreateSubscription(ctx context.Context, request CreateSubscriptionRequestObject) (CreateSubscriptionResponseObject, error)
	// GetSubscription Read a Subscription
	// (GET /fhir/Subscription/{id})
	GetSubscription(ctx context.Context, request GetSubscriptionRequestObject) (GetSubscriptionResponseObject, error)
	// GetSubscriptionEvents Replay events ($events)
	// (GET /fhir/Subscription/{id}/$events)
	GetSubscriptionEvents(ctx context.Context, request GetSubscriptionEventsRequestObject) (GetSubscriptionEventsResponseObject, error)
	// GetSubscriptionStatus Query subscription status ($status)
	// (GET /fhir/Subscription/{id}/$status)
	GetSubscriptionStatus(ctx context.Context, request GetSubscriptionStatusRequestObject) (GetSubscriptionStatusResponseObject, error)
	// GetSubscriptionTopic Read an agreed SubscriptionTopic
	// (GET /fhir/SubscriptionTopic/{id})
	GetSubscriptionTopic(ctx context.Context, request GetSubscriptionTopicRequestObject) (GetSubscriptionTopicResponseObject, error)
	// ReadAliasedTask Read a Task by its aliased (opaque) id
	// (GET /fhir/Task/{id})
	ReadAliasedTask(ctx context.Context, request ReadAliasedTaskRequestObject) (ReadAliasedTaskResponseObject, error)
	// ReceiveNotification Receive a notification Bundle (rest-hook endpoint)
	// (POST /fhir/notifications)
	ReceiveNotification(ctx context.Context, request ReceiveNotificationRequestObject) (ReceiveNotificationResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateSubscription operation middleware
func (sh *strictHandler) CreateSubscription(w http.ResponseWriter, r *http.Request) {
	var request CreateSubscriptionRequestObject

	var body CreateSubscriptionApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscription(ctx, request.(CreateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSubscriptionResponseObject); ok {
		if err := validResponse.VisitCreateSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscription operation middleware
func (sh *strictHandler) GetSubscription(w http.ResponseWriter, r *http.Request, id SubscriptionID) {
	var request GetSubscriptionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscription(ctx, request.(GetSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscriptionEvents operation middleware
func (sh *strictHandler) GetSubscriptionEvents(w http.ResponseWriter, r *http.Request, id SubscriptionID, params GetSubscriptionEventsParams) {
	var request GetSubscriptionEventsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscriptionEvents(ctx, request.(GetSubscriptionEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscriptionEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionEventsResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscriptionStatus operation middleware
func (sh *strictHandler) GetSubscriptionStatus(w http.ResponseWriter, r *http.Request, id SubscriptionID) {
	var request GetSubscriptionStatusRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscriptionStatus(ctx, request.(GetSubscriptionStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscriptionStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionStatusResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSubscriptionTopic operation middleware
func (sh *strictHandler) GetSubscriptionTopic(w http.ResponseWriter, r *http.Request, id string) {
	var request GetSubscriptionTopicRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscriptionTopic(ctx, request.(GetSubscriptionTopicRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscriptionTopic")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSubscriptionTopicResponseObject); ok {
		if err := validResponse.VisitGetSubscriptionTopicResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReadAliasedTask operation middleware
func (sh *strictHandler) ReadAliasedTask(w http.ResponseWriter, r *http.Request, id string) {
	var request ReadAliasedTaskRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReadAliasedTask(ctx, request.(ReadAliasedTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReadAliasedTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadAliasedTaskResponseObject); ok {
		if err := validResponse.VisitReadAliasedTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveNotification operation middleware
func (sh *strictHandler) ReceiveNotification(w http.ResponseWriter, r *http.Request) {
	var request ReceiveNotificationRequestObject

	var body ReceiveNotificationApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveNotification(ctx, request.(ReceiveNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveNotification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveNotificationResponseObject); ok {
		if err := validResponse.VisitReceiveNotificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
