//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	"github.com/zorgbijjou/golang-fhir-models/fhir-models/fhir"
)

// Defines values for PDPAuthzResponsePoliciesReasonsCode.
const (
	Info            PDPAuthzResponsePoliciesReasonsCode = "info"
	InternalError   PDPAuthzResponsePoliciesReasonsCode = "internal_error"
	NotAllowed      PDPAuthzResponsePoliciesReasonsCode = "not_allowed"
	NotImplemented  PDPAuthzResponsePoliciesReasonsCode = "not_implemented"
	PipError        PDPAuthzResponsePoliciesReasonsCode = "pip_error"
	UnexpectedInput PDPAuthzResponsePoliciesReasonsCode = "unexpected_input"
)

// Valid indicates whether the value is a known member of the PDPAuthzResponsePoliciesReasonsCode enum.
func (e PDPAuthzResponsePoliciesReasonsCode) Valid() bool {
	switch e {
	case Info:
		return true
	case InternalError:
		return true
	case NotAllowed:
		return true
	case NotImplemented:
		return true
	case PipError:
		return true
	case UnexpectedInput:
		return true
	default:
		return false
	}
}

// DirectoryUpdateReport Result of one LRZA sync cycle.
//
// Example: {"created":1,"deleted":0,"errors":[],"updated":5,"warnings":["Some-warning-message"]}
type DirectoryUpdateReport struct {
	// Created Number of resources created in the Query Directory.
	//
	// Example: 1
	Created *int `json:"created,omitempty"`

	// Deleted Number of resources deleted from the Query Directory.
	//
	// Example: 0
	Deleted *int `json:"deleted,omitempty"`

	// Errors Fatal issues encountered during the sync.
	//
	// Example: []
	Errors *[]string `json:"errors,omitempty"`

	// Updated Number of resources updated in the Query Directory.
	//
	// Example: 5
	Updated *int `json:"updated,omitempty"`

	// Warnings Non-fatal issues encountered during the sync.
	//
	// Example: ["Some-warning-message"]
	Warnings *[]string `json:"warnings,omitempty"`
}

// FHIRBundle A FHIR R4 Bundle resource. See https://hl7.org/fhir/R4/bundle.html for its schema; not redefined here.
type FHIRBundle = fhir.Bundle

// FHIRList A FHIR R4 List resource (see https://hl7.org/fhir/R4/list.html for its schema; not redefined here). Used here as a pointer: it declares that data of a given category exists for a patient at the custodian organization, without carrying the patient data itself.
//
// Example: {"code":{"coding":[{"code":"MedicationRequest","system":"http://minvws.github.io/generiekefuncties-docs/CodeSystem/nl-gf-data-categories-cs"}]},"extension":[{"url":"http://minvws.github.io/generiekefuncties-docs/StructureDefinition/nl-gf-localization-custodian","valueReference":{"identifier":{"system":"http://fhir.nl/fhir/NamingSystem/ura","value":"00000020"}}}],"mode":"working","resourceType":"List","source":{"identifier":{"system":"http://fhir.nl/fhir/NamingSystem/ura","value":"00000020"}},"status":"current","subject":{"identifier":{"system":"http://fhir.nl/fhir/NamingSystem/bsn","value":"999911136"}}}
type FHIRList = fhir.List

// FHIROperationOutcome A FHIR R4 OperationOutcome resource, returned for error responses. See https://hl7.org/fhir/R4/operationoutcome.html for its schema; not redefined here.
//
// Example: {"issue":[{"code":"value","diagnostics":"missing tenant request header: X-Tenant-ID","severity":"error"}],"resourceType":"OperationOutcome"}
type FHIROperationOutcome = fhir.OperationOutcome

// FHIRSubscription A FHIR R4 Subscription resource. See https://hl7.org/fhir/R4/subscription.html for its schema; not redefined here.
type FHIRSubscription = fhir.Subscription

// PDPAuthzRequest defines model for PDPAuthzRequest.
type PDPAuthzRequest struct {
	Input struct {
		// Context Additional context for the authorization decision, not captured by the `request` object itself.
		Context struct {
			// ConnectionTypeCode Type of connection used for the request. Should be a code from the HL7 EndpointConnectionType code system (http://terminology.hl7.org/CodeSystem/endpoint-connection-type) where applicable.
			//
			//
			// Example: hl7-fhir-rest
			ConnectionTypeCode string `json:"connection_type_code"`

			// DataHolderFacilityType Facility type of the data holder's organization, from the Vektis facility type code system.
			//
			//
			// Example: Z3
			DataHolderFacilityType *string `json:"data_holder_facility_type,omitempty"`

			// DataHolderOrganizationId URA number identifying the data holder's organization.
			//
			// Example: 00000659
			DataHolderOrganizationId string `json:"data_holder_organization_id"`

			// PatientBsn BSN of the patient the request concerns, if already known by the caller. Uses the naming system `http://fhir.nl/fhir/NamingSystem/bsn`.
			//
			//
			// Example: 999911136
			PatientBsn *string `json:"patient_bsn,omitempty"`
		} `json:"context"`

		// Request The HTTP request that is being authorized (e.g. FHIR request).
		Request struct {
			// Body Raw request body. Only read when `Content-Type` is `application/x-www-form-urlencoded`, to extract search or operation parameters; ignored otherwise.
			//
			//
			// Example: identifier=http://fhir.nl/fhir/NamingSystem/bsn|900214181
			Body *string `json:"body,omitempty"`

			// Header HTTP headers of the request being authorized, each value an array of strings. Only `Content-Type` is currently inspected, to detect form-encoded search/operation bodies.
			//
			//
			// Example: {"Content-Type":["application/x-www-form-urlencoded"]}
			Header *map[string][]string `json:"header,omitempty"`

			// Method HTTP method of the request being authorized.
			//
			// Example: GET
			Method string `json:"method"`

			// Path Path of the request. For a FHIR request, this is relative to the FHIR RESTful root (e.g. `/Patient/123`) — it does not include any additional application path prefix such as `/fhir`. Does not include the query string.
			//
			//
			// Example: /Patient/3E439979-017F-40AA-594D-EBCF880FFD97
			Path string `json:"path"`

			// Protocol HTTP protocol version of the request being authorized.
			//
			// Example: HTTP/1.1
			Protocol string `json:"protocol"`

			// Query Raw query string of the request being authorized (e.g. `_since=2024-01-01`), without the leading `?`.
			//
			//
			// Example: _since=2024-01-01
			Query *string `json:"query,omitempty"`
		} `json:"request"`

		// Subject The user and organization on whose behalf the request is being made. Additional unrecognized properties are passed through as-is.
		// In the reference PEP setup, this is sourced directly from the Nuts node's token introspection response (`POST /nuts/auth/v2/accesstoken/introspect`) — no transformation needed.
		Subject PDPAuthzRequest_Input_Subject `json:"subject"`
	} `json:"input"`
}

// PDPAuthzRequest_Input_Subject The user and organization on whose behalf the request is being made. Additional unrecognized properties are passed through as-is.
// In the reference PEP setup, this is sourced directly from the Nuts node's token introspection response (`POST /nuts/auth/v2/accesstoken/introspect`) — no transformation needed.
type PDPAuthzRequest_Input_Subject struct {
	// Active Whether the access token backing this request is currently active.
	//
	// Example: true
	Active *bool `json:"active,omitempty"`

	// ClientId Identifier of the requesting application, e.g. the OAuth2 `client_id` of the client that obtained the access token.
	//
	//
	// Example: gp-portal-client
	ClientId *string `json:"client_id,omitempty"`

	// OrganizationFacilityType Facility type of the requester's organization, from the Vektis facility type code system.
	//
	//
	// Example: Z3
	OrganizationFacilityType *string `json:"organization_facility_type,omitempty"`

	// OrganizationName Display name of the requester's organization.
	//
	// Example: Huisartsenpraktijk Voorbeeld
	OrganizationName *string `json:"organization_name,omitempty"`

	// OrganizationUra URA number identifying the requester's organization.
	//
	// Example: 00000666
	OrganizationUra *string `json:"organization_ura,omitempty"`

	// Scope Space-separated list of OAuth2 scopes, each naming a policy to evaluate (e.g. `bgz`, `mcsd_update`, `pzp_gf`).
	//
	//
	// Example: bgz
	Scope *string `json:"scope,omitempty"`

	// UserId Identifier of the practitioner performing the request (CIBG Dezi-nummer or UZI number).
	//
	//
	// Example: 000095254
	UserId *string `json:"user_id,omitempty"`

	// UserRole Role of the practitioner, from the CIBG Dezi / BIG-register.
	//
	//
	// Example: 01.015
	UserRole             *string                `json:"user_role,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PDPAuthzResponse defines model for PDPAuthzResponse.
type PDPAuthzResponse struct {
	// Allow Overall decision: whether the request being authorized is allowed. This is the only field the PEP is required to honor.
	//
	//
	// Example: true
	Allow *bool `json:"allow,omitempty"`

	// Error Set when the request could not be evaluated (e.g. malformed input).
	//
	// Example: unable to parse FHIR request
	Error *string `json:"error,omitempty"`

	// Policies Per-policy evaluation results, keyed by policy (scope) name. Non-normative: informational, not required to be honored by the PEP.
	Policies *map[string]struct {
		// Allow Whether this specific policy allows the request.
		//
		// Example: true
		Allow *bool `json:"allow,omitempty"`

		// Reasons Explanations for the policy's decision.
		Reasons *[]struct {
			// Code Machine-readable reason code. `info` accompanies an allow; the others accompany a denial or evaluation failure. Implementations may extend this list with additional codes.
			//
			//
			// Example: info
			Code *PDPAuthzResponsePoliciesReasonsCode `json:"code,omitempty"`

			// Description Human-readable explanation of the reason code.
			//
			// Example: MITZ consent granted
			Description *string `json:"description,omitempty"`
		} `json:"reasons,omitempty"`
	} `json:"policies,omitempty"`
}

// PDPAuthzResponsePoliciesReasonsCode Machine-readable reason code. `info` accompanies an allow; the others accompany a denial or evaluation failure. Implementations may extend this list with additional codes.
//
// Example: info
type PDPAuthzResponsePoliciesReasonsCode string

// Count defines model for Count.
type Count = int

// TenantID defines model for TenantID.
type TenantID = string

// OperationOutcomeError A FHIR R4 OperationOutcome resource, returned for error responses. See https://hl7.org/fhir/R4/operationoutcome.html for its schema; not redefined here.
//
// Example: {"issue":[{"code":"value","diagnostics":"missing tenant request header: X-Tenant-ID","severity":"error"}],"resourceType":"OperationOutcome"}
type OperationOutcomeError = FHIROperationOutcome

// RegisterNVIListBundleParams defines parameters for RegisterNVIListBundle.
type RegisterNVIListBundleParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// DeleteNVIListsByParamsParams defines parameters for DeleteNVIListsByParams.
type DeleteNVIListsByParamsParams struct {
	// PatientIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). Mapped to `subject:identifier` before forwarding to NVI.
	PatientIdentifier *string `form:"patient:identifier,omitempty" json:"patient:identifier,omitempty"`

	// SubjectIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). NVI's native parameter name; equivalent to `patient:identifier`.
	SubjectIdentifier *string `form:"subject:identifier,omitempty" json:"subject:identifier,omitempty"`

	// SourceIdentifier Identifier of `List.source` (the system that registered the List), as a FHIR token (`system|value`).
	SourceIdentifier *string `form:"source:identifier,omitempty" json:"source:identifier,omitempty"`

	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// SearchNVIListsParams defines parameters for SearchNVILists.
type SearchNVIListsParams struct {
	// PatientIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). Mapped to `subject:identifier` before forwarding to NVI.
	PatientIdentifier *string `form:"patient:identifier,omitempty" json:"patient:identifier,omitempty"`

	// SubjectIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). NVI's native parameter name; equivalent to `patient:identifier`.
	SubjectIdentifier *string `form:"subject:identifier,omitempty" json:"subject:identifier,omitempty"`

	// SourceIdentifier Identifier of `List.source` (the system that registered the List), as a FHIR token (`system|value`).
	SourceIdentifier *string `form:"source:identifier,omitempty" json:"source:identifier,omitempty"`

	// Code `List.code` search parameter, to filter by list/data category (e.g. `MedicationRequest`).
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// UnderscoreCount FHIR `_count` search parameter: maximum number of results per page. Forwarded to NVI as-is.
	UnderscoreCount *Count `form:"_count,omitempty" json:"_count,omitempty"`

	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// RegisterNVIListParams defines parameters for RegisterNVIList.
type RegisterNVIListParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// SearchNVIListsFormFormdataBody defines parameters for SearchNVIListsForm.
type SearchNVIListsFormFormdataBody struct {
	// UnderscoreCount FHIR `_count` search parameter: maximum number of results per page. Forwarded to NVI as-is.
	//
	//
	// Example: 20
	UnderscoreCount   *int    `form:"_count,omitempty" json:"_count,omitempty"`
	Code              *string `form:"code,omitempty" json:"code,omitempty"`
	PatientIdentifier *string `form:"patient:identifier,omitempty" json:"patient:identifier,omitempty"`
	SourceIdentifier  *string `form:"source:identifier,omitempty" json:"source:identifier,omitempty"`
	SubjectIdentifier *string `form:"subject:identifier,omitempty" json:"subject:identifier,omitempty"`
}

// SearchNVIListsFormParams defines parameters for SearchNVIListsForm.
type SearchNVIListsFormParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// DeleteNVIListParams defines parameters for DeleteNVIList.
type DeleteNVIListParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// GetNVIListParams defines parameters for GetNVIList.
type GetNVIListParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody defines body for CreateMitzSubscription for application/fhir+json ContentType.
type CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody = FHIRSubscription

// RegisterNVIListBundleApplicationFhirPlusJSONRequestBody defines body for RegisterNVIListBundle for application/fhir+json ContentType.
type RegisterNVIListBundleApplicationFhirPlusJSONRequestBody = FHIRBundle

// RegisterNVIListApplicationFhirPlusJSONRequestBody defines body for RegisterNVIList for application/fhir+json ContentType.
type RegisterNVIListApplicationFhirPlusJSONRequestBody = FHIRList

// SearchNVIListsFormFormdataRequestBody defines body for SearchNVIListsForm for application/x-www-form-urlencoded ContentType.
type SearchNVIListsFormFormdataRequestBody SearchNVIListsFormFormdataBody

// EvaluateAuthorizationDirectJSONRequestBody defines body for EvaluateAuthorizationDirect for application/json ContentType.
type EvaluateAuthorizationDirectJSONRequestBody = PDPAuthzRequest

// EvaluateAuthorizationJSONRequestBody defines body for EvaluateAuthorization for application/json ContentType.
type EvaluateAuthorizationJSONRequestBody = PDPAuthzRequest

// Getter for additional properties for PDPAuthzRequest_Input_Subject. Returns the specified
// element and whether it was found
func (a PDPAuthzRequest_Input_Subject) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PDPAuthzRequest_Input_Subject
func (a *PDPAuthzRequest_Input_Subject) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PDPAuthzRequest_Input_Subject to handle AdditionalProperties
func (a *PDPAuthzRequest_Input_Subject) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["active"]; found {
		err = json.Unmarshal(raw, &a.Active)
		if err != nil {
			return fmt.Errorf("error reading 'active': %w", err)
		}
		delete(object, "active")
	}

	if raw, found := object["client_id"]; found {
		err = json.Unmarshal(raw, &a.ClientId)
		if err != nil {
			return fmt.Errorf("error reading 'client_id': %w", err)
		}
		delete(object, "client_id")
	}

	if raw, found := object["organization_facility_type"]; found {
		err = json.Unmarshal(raw, &a.OrganizationFacilityType)
		if err != nil {
			return fmt.Errorf("error reading 'organization_facility_type': %w", err)
		}
		delete(object, "organization_facility_type")
	}

	if raw, found := object["organization_name"]; found {
		err = json.Unmarshal(raw, &a.OrganizationName)
		if err != nil {
			return fmt.Errorf("error reading 'organization_name': %w", err)
		}
		delete(object, "organization_name")
	}

	if raw, found := object["organization_ura"]; found {
		err = json.Unmarshal(raw, &a.OrganizationUra)
		if err != nil {
			return fmt.Errorf("error reading 'organization_ura': %w", err)
		}
		delete(object, "organization_ura")
	}

	if raw, found := object["scope"]; found {
		err = json.Unmarshal(raw, &a.Scope)
		if err != nil {
			return fmt.Errorf("error reading 'scope': %w", err)
		}
		delete(object, "scope")
	}

	if raw, found := object["user_id"]; found {
		err = json.Unmarshal(raw, &a.UserId)
		if err != nil {
			return fmt.Errorf("error reading 'user_id': %w", err)
		}
		delete(object, "user_id")
	}

	if raw, found := object["user_role"]; found {
		err = json.Unmarshal(raw, &a.UserRole)
		if err != nil {
			return fmt.Errorf("error reading 'user_role': %w", err)
		}
		delete(object, "user_role")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PDPAuthzRequest_Input_Subject to handle AdditionalProperties
func (a PDPAuthzRequest_Input_Subject) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Active != nil {
		object["active"], err = json.Marshal(a.Active)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'active': %w", err)
		}
	}

	if a.ClientId != nil {
		object["client_id"], err = json.Marshal(a.ClientId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'client_id': %w", err)
		}
	}

	if a.OrganizationFacilityType != nil {
		object["organization_facility_type"], err = json.Marshal(a.OrganizationFacilityType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'organization_facility_type': %w", err)
		}
	}

	if a.OrganizationName != nil {
		object["organization_name"], err = json.Marshal(a.OrganizationName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'organization_name': %w", err)
		}
	}

	if a.OrganizationUra != nil {
		object["organization_ura"], err = json.Marshal(a.OrganizationUra)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'organization_ura': %w", err)
		}
	}

	if a.Scope != nil {
		object["scope"], err = json.Marshal(a.Scope)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scope': %w", err)
		}
	}

	if a.UserId != nil {
		object["user_id"], err = json.Marshal(a.UserId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'user_id': %w", err)
		}
	}

	if a.UserRole != nil {
		object["user_role"], err = json.Marshal(a.UserRole)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'user_role': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// TriggerLrzaSync Trigger LRZA synchronization
	// (POST /lrza/update)
	TriggerLrzaSync(w http.ResponseWriter, r *http.Request)
	// CreateMitzSubscription Create a MITZ consent subscription
	// (POST /mitz/Subscription)
	CreateMitzSubscription(w http.ResponseWriter, r *http.Request)
	// RegisterNVIListBundle Register a List via a transaction Bundle
	// (POST /nvi)
	RegisterNVIListBundle(w http.ResponseWriter, r *http.Request, params RegisterNVIListBundleParams)
	// DeleteNVIListsByParams Delete Lists matching search parameters
	// (DELETE /nvi/List)
	DeleteNVIListsByParams(w http.ResponseWriter, r *http.Request, params DeleteNVIListsByParamsParams)
	// SearchNVILists Search for Lists
	// (GET /nvi/List)
	SearchNVILists(w http.ResponseWriter, r *http.Request, params SearchNVIListsParams)
	// RegisterNVIList Register a List directly
	// (POST /nvi/List)
	RegisterNVIList(w http.ResponseWriter, r *http.Request, params RegisterNVIListParams)
	// SearchNVIListsForm Search for Lists (form-encoded body)
	// (POST /nvi/List/_search)
	SearchNVIListsForm(w http.ResponseWriter, r *http.Request, params SearchNVIListsFormParams)
	// DeleteNVIList Delete a List by ID
	// (DELETE /nvi/List/{id})
	DeleteNVIList(w http.ResponseWriter, r *http.Request, id string, params DeleteNVIListParams)
	// GetNVIList Read a List by ID
	// (GET /nvi/List/{id})
	GetNVIList(w http.ResponseWriter, r *http.Request, id string, params GetNVIListParams)
	// EvaluateAuthorizationDirect Evaluate an authorization request (shorthand alias)
	// (POST /pdp)
	EvaluateAuthorizationDirect(w http.ResponseWriter, r *http.Request)
	// ListAuthorizationPolicyBundles List loaded policy bundles
	// (GET /pdp/bundles)
	ListAuthorizationPolicyBundles(w http.ResponseWriter, r *http.Request)
	// GetAuthorizationPolicyBundle Get a loaded policy bundle by name
	// (GET /pdp/bundles/{policyName})
	GetAuthorizationPolicyBundle(w http.ResponseWriter, r *http.Request, policyName string)
	// EvaluateAuthorization Evaluate an authorization request
	// (POST /pdp/v1/data/knooppunt/authz)
	EvaluateAuthorization(w http.ResponseWriter, r *http.Request)
	// GetStatus Readiness check
	// (GET /status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// GetVersion Build version info
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// TriggerLrzaSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerLrzaSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerLrzaSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMitzSubscription operation middleware
func (siw *ServerInterfaceWrapper) CreateMitzSubscription(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMitzSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterNVIListBundle operation middleware
func (siw *ServerInterfaceWrapper) RegisterNVIListBundle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterNVIListBundleParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterNVIListBundle(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNVIListsByParams operation middleware
func (siw *ServerInterfaceWrapper) DeleteNVIListsByParams(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteNVIListsByParamsParams

	// ------------- Optional query parameter "patient:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "patient:identifier", r.URL.Query(), &params.PatientIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "patient:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "patient:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "subject:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject:identifier", r.URL.Query(), &params.SubjectIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "subject:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source:identifier", r.URL.Query(), &params.SourceIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source:identifier", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNVIListsByParams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchNVILists operation middleware
func (siw *ServerInterfaceWrapper) SearchNVILists(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchNVIListsParams

	// ------------- Optional query parameter "patient:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "patient:identifier", r.URL.Query(), &params.PatientIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "patient:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "patient:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "subject:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject:identifier", r.URL.Query(), &params.SubjectIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "subject:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source:identifier", r.URL.Query(), &params.SourceIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "_count" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "_count", r.URL.Query(), &params.UnderscoreCount, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "_count"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "_count", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchNVILists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterNVIList operation middleware
func (siw *ServerInterfaceWrapper) RegisterNVIList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterNVIListParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterNVIList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchNVIListsForm operation middleware
func (siw *ServerInterfaceWrapper) SearchNVIListsForm(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchNVIListsFormParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchNVIListsForm(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNVIList operation middleware
func (siw *ServerInterfaceWrapper) DeleteNVIList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteNVIListParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNVIList(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNVIList operation middleware
func (siw *ServerInterfaceWrapper) GetNVIList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNVIListParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNVIList(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EvaluateAuthorizationDirect operation middleware
func (siw *ServerInterfaceWrapper) EvaluateAuthorizationDirect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EvaluateAuthorizationDirect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuthorizationPolicyBundles operation middleware
func (siw *ServerInterfaceWrapper) ListAuthorizationPolicyBundles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuthorizationPolicyBundles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthorizationPolicyBundle operation middleware
func (siw *ServerInterfaceWrapper) GetAuthorizationPolicyBundle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "policyName" -------------
	var policyName string

	err = runtime.BindStyledParameterWithOptions("simple", "policyName", r.PathValue("policyName"), &policyName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthorizationPolicyBundle(w, r, policyName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EvaluateAuthorization operation middleware
func (siw *ServerInterfaceWrapper) EvaluateAuthorization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EvaluateAuthorization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/lrza/update", wrapper.TriggerLrzaSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/pdp", wrapper.EvaluateAuthorizationDirect)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/pdp/v1/data/knooppunt/authz", wrapper.EvaluateAuthorization)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pdp/bundles", wrapper.ListAuthorizationPolicyBundles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pdp/bundles/{policyName}", wrapper.GetAuthorizationPolicyBundle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/nvi", wrapper.RegisterNVIListBundle)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/nvi/List", wrapper.DeleteNVIListsByParams)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/nvi/List", wrapper.SearchNVILists)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/nvi/List", wrapper.RegisterNVIList)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/nvi/List/_search", wrapper.SearchNVIListsForm)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/nvi/List/{id}", wrapper.DeleteNVIList)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/nvi/List/{id}", wrapper.GetNVIList)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/mitz/Subscription", wrapper.CreateMitzSubscription)

	return m
}

type OperationOutcomeErrorApplicationFhirPlusJSONResponse FHIROperationOutcome

type TriggerLrzaSyncRequestObject struct {
}

type TriggerLrzaSyncResponseObject interface {
	VisitTriggerLrzaSyncResponse(w http.ResponseWriter) error
}

type TriggerLrzaSync200JSONResponse DirectoryUpdateReport

func (response TriggerLrzaSync200JSONResponse) VisitTriggerLrzaSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerLrzaSync500TextResponse string

func (response TriggerLrzaSync500TextResponse) VisitTriggerLrzaSyncResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type CreateMitzSubscriptionRequestObject struct {
	Body *CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody
}

type CreateMitzSubscriptionResponseObject interface {
	VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error
}

type CreateMitzSubscription201ApplicationFhirPlusJSONResponse FHIRSubscription

func (response CreateMitzSubscription201ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMitzSubscription400ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response CreateMitzSubscription400ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMitzSubscription500ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response CreateMitzSubscription500ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMitzSubscription503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response CreateMitzSubscription503ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIListBundleRequestObject struct {
	Params RegisterNVIListBundleParams
	Body   *RegisterNVIListBundleApplicationFhirPlusJSONRequestBody
}

type RegisterNVIListBundleResponseObject interface {
	VisitRegisterNVIListBundleResponse(w http.ResponseWriter) error
}

type RegisterNVIListBundle200ApplicationFhirPlusJSONResponse FHIRBundle

func (response RegisterNVIListBundle200ApplicationFhirPlusJSONResponse) VisitRegisterNVIListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIListBundle400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response RegisterNVIListBundle400ApplicationFhirPlusJSONResponse) VisitRegisterNVIListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIListBundle500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterNVIListBundle500ApplicationFhirPlusJSONResponse) VisitRegisterNVIListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIListBundle503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterNVIListBundle503ApplicationFhirPlusJSONResponse) VisitRegisterNVIListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNVIListsByParamsRequestObject struct {
	Params DeleteNVIListsByParamsParams
}

type DeleteNVIListsByParamsResponseObject interface {
	VisitDeleteNVIListsByParamsResponse(w http.ResponseWriter) error
}

type DeleteNVIListsByParams204Response struct {
}

func (response DeleteNVIListsByParams204Response) VisitDeleteNVIListsByParamsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteNVIListsByParams400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response DeleteNVIListsByParams400ApplicationFhirPlusJSONResponse) VisitDeleteNVIListsByParamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNVIListsByParams500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteNVIListsByParams500ApplicationFhirPlusJSONResponse) VisitDeleteNVIListsByParamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNVIListsByParams503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteNVIListsByParams503ApplicationFhirPlusJSONResponse) VisitDeleteNVIListsByParamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVIListsRequestObject struct {
	Params SearchNVIListsParams
}

type SearchNVIListsResponseObject interface {
	VisitSearchNVIListsResponse(w http.ResponseWriter) error
}

type SearchNVILists200ApplicationFhirPlusJSONResponse FHIRBundle

func (response SearchNVILists200ApplicationFhirPlusJSONResponse) VisitSearchNVIListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVILists400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response SearchNVILists400ApplicationFhirPlusJSONResponse) VisitSearchNVIListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVILists422ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchNVILists422ApplicationFhirPlusJSONResponse) VisitSearchNVIListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVILists500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchNVILists500ApplicationFhirPlusJSONResponse) VisitSearchNVIListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVILists503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchNVILists503ApplicationFhirPlusJSONResponse) VisitSearchNVIListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIListRequestObject struct {
	Params RegisterNVIListParams
	Body   *RegisterNVIListApplicationFhirPlusJSONRequestBody
}

type RegisterNVIListResponseObject interface {
	VisitRegisterNVIListResponse(w http.ResponseWriter) error
}

type RegisterNVIList200ApplicationFhirPlusJSONResponse FHIRList

func (response RegisterNVIList200ApplicationFhirPlusJSONResponse) VisitRegisterNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIList400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response RegisterNVIList400ApplicationFhirPlusJSONResponse) VisitRegisterNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIList500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterNVIList500ApplicationFhirPlusJSONResponse) VisitRegisterNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterNVIList503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterNVIList503ApplicationFhirPlusJSONResponse) VisitRegisterNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVIListsFormRequestObject struct {
	Params SearchNVIListsFormParams
	Body   *SearchNVIListsFormFormdataRequestBody
}

type SearchNVIListsFormResponseObject interface {
	VisitSearchNVIListsFormResponse(w http.ResponseWriter) error
}

type SearchNVIListsForm200ApplicationFhirPlusJSONResponse FHIRBundle

func (response SearchNVIListsForm200ApplicationFhirPlusJSONResponse) VisitSearchNVIListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVIListsForm400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response SearchNVIListsForm400ApplicationFhirPlusJSONResponse) VisitSearchNVIListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVIListsForm422ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchNVIListsForm422ApplicationFhirPlusJSONResponse) VisitSearchNVIListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVIListsForm500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchNVIListsForm500ApplicationFhirPlusJSONResponse) VisitSearchNVIListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchNVIListsForm503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchNVIListsForm503ApplicationFhirPlusJSONResponse) VisitSearchNVIListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNVIListRequestObject struct {
	Id     string `json:"id"`
	Params DeleteNVIListParams
}

type DeleteNVIListResponseObject interface {
	VisitDeleteNVIListResponse(w http.ResponseWriter) error
}

type DeleteNVIList204Response struct {
}

func (response DeleteNVIList204Response) VisitDeleteNVIListResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteNVIList400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response DeleteNVIList400ApplicationFhirPlusJSONResponse) VisitDeleteNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNVIList500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteNVIList500ApplicationFhirPlusJSONResponse) VisitDeleteNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteNVIList503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteNVIList503ApplicationFhirPlusJSONResponse) VisitDeleteNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetNVIListRequestObject struct {
	Id     string `json:"id"`
	Params GetNVIListParams
}

type GetNVIListResponseObject interface {
	VisitGetNVIListResponse(w http.ResponseWriter) error
}

type GetNVIList200ApplicationFhirPlusJSONResponse FHIRList

func (response GetNVIList200ApplicationFhirPlusJSONResponse) VisitGetNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetNVIList400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response GetNVIList400ApplicationFhirPlusJSONResponse) VisitGetNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetNVIList500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response GetNVIList500ApplicationFhirPlusJSONResponse) VisitGetNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetNVIList503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response GetNVIList503ApplicationFhirPlusJSONResponse) VisitGetNVIListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type EvaluateAuthorizationDirectRequestObject struct {
	Body *EvaluateAuthorizationDirectJSONRequestBody
}

type EvaluateAuthorizationDirectResponseObject interface {
	VisitEvaluateAuthorizationDirectResponse(w http.ResponseWriter) error
}

type EvaluateAuthorizationDirect200JSONResponse PDPAuthzResponse

func (response EvaluateAuthorizationDirect200JSONResponse) VisitEvaluateAuthorizationDirectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EvaluateAuthorizationDirect400JSONResponse PDPAuthzResponse

func (response EvaluateAuthorizationDirect400JSONResponse) VisitEvaluateAuthorizationDirectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListAuthorizationPolicyBundlesRequestObject struct {
}

type ListAuthorizationPolicyBundlesResponseObject interface {
	VisitListAuthorizationPolicyBundlesResponse(w http.ResponseWriter) error
}

type ListAuthorizationPolicyBundles200JSONResponse []string

func (response ListAuthorizationPolicyBundles200JSONResponse) VisitListAuthorizationPolicyBundlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthorizationPolicyBundleRequestObject struct {
	PolicyName string `json:"policyName"`
}

type GetAuthorizationPolicyBundleResponseObject interface {
	VisitGetAuthorizationPolicyBundleResponse(w http.ResponseWriter) error
}

type GetAuthorizationPolicyBundle200Response struct {
}

func (response GetAuthorizationPolicyBundle200Response) VisitGetAuthorizationPolicyBundleResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetAuthorizationPolicyBundle404Response struct {
}

func (response GetAuthorizationPolicyBundle404Response) VisitGetAuthorizationPolicyBundleResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type EvaluateAuthorizationRequestObject struct {
	Body *EvaluateAuthorizationJSONRequestBody
}

type EvaluateAuthorizationResponseObject interface {
	VisitEvaluateAuthorizationResponse(w http.ResponseWriter) error
}

type EvaluateAuthorization200JSONResponse PDPAuthzResponse

func (response EvaluateAuthorization200JSONResponse) VisitEvaluateAuthorizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EvaluateAuthorization400JSONResponse PDPAuthzResponse

func (response EvaluateAuthorization400JSONResponse) VisitEvaluateAuthorizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusRequestObject struct {
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus200TextResponse string

func (response GetStatus200TextResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetStatus503TextResponse string

func (response GetStatus503TextResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(503)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200TextResponse string

func (response GetVersion200TextResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// TriggerLrzaSync Trigger LRZA synchronization
	// (POST /lrza/update)
	TriggerLrzaSync(ctx context.Context, request TriggerLrzaSyncRequestObject) (TriggerLrzaSyncResponseObject, error)
	// CreateMitzSubscription Create a MITZ consent subscription
	// (POST /mitz/Subscription)
	CreateMitzSubscription(ctx context.Context, request CreateMitzSubscriptionRequestObject) (CreateMitzSubscriptionResponseObject, error)
	// RegisterNVIListBundle Register a List via a transaction Bundle
	// (POST /nvi)
	RegisterNVIListBundle(ctx context.Context, request RegisterNVIListBundleRequestObject) (RegisterNVIListBundleResponseObject, error)
	// DeleteNVIListsByParams Delete Lists matching search parameters
	// (DELETE /nvi/List)
	DeleteNVIListsByParams(ctx context.Context, request DeleteNVIListsByParamsRequestObject) (DeleteNVIListsByParamsResponseObject, error)
	// SearchNVILists Search for Lists
	// (GET /nvi/List)
	SearchNVILists(ctx context.Context, request SearchNVIListsRequestObject) (SearchNVIListsResponseObject, error)
	// RegisterNVIList Register a List directly
	// (POST /nvi/List)
	RegisterNVIList(ctx context.Context, request RegisterNVIListRequestObject) (RegisterNVIListResponseObject, error)
	// SearchNVIListsForm Search for Lists (form-encoded body)
	// (POST /nvi/List/_search)
	SearchNVIListsForm(ctx context.Context, request SearchNVIListsFormRequestObject) (SearchNVIListsFormResponseObject, error)
	// DeleteNVIList Delete a List by ID
	// (DELETE /nvi/List/{id})
	DeleteNVIList(ctx context.Context, request DeleteNVIListRequestObject) (DeleteNVIListResponseObject, error)
	// GetNVIList Read a List by ID
	// (GET /nvi/List/{id})
	GetNVIList(ctx context.Context, request GetNVIListRequestObject) (GetNVIListResponseObject, error)
	// EvaluateAuthorizationDirect Evaluate an authorization request (shorthand alias)
	// (POST /pdp)
	EvaluateAuthorizationDirect(ctx context.Context, request EvaluateAuthorizationDirectRequestObject) (EvaluateAuthorizationDirectResponseObject, error)
	// ListAuthorizationPolicyBundles List loaded policy bundles
	// (GET /pdp/bundles)
	ListAuthorizationPolicyBundles(ctx context.Context, request ListAuthorizationPolicyBundlesRequestObject) (ListAuthorizationPolicyBundlesResponseObject, error)
	// GetAuthorizationPolicyBundle Get a loaded policy bundle by name
	// (GET /pdp/bundles/{policyName})
	GetAuthorizationPolicyBundle(ctx context.Context, request GetAuthorizationPolicyBundleRequestObject) (GetAuthorizationPolicyBundleResponseObject, error)
	// EvaluateAuthorization Evaluate an authorization request
	// (POST /pdp/v1/data/knooppunt/authz)
	EvaluateAuthorization(ctx context.Context, request EvaluateAuthorizationRequestObject) (EvaluateAuthorizationResponseObject, error)
	// GetStatus Readiness check
	// (GET /status)
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// GetVersion Build version info
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// TriggerLrzaSync operation middleware
func (sh *strictHandler) TriggerLrzaSync(w http.ResponseWriter, r *http.Request) {
	var request TriggerLrzaSyncRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerLrzaSync(ctx, request.(TriggerLrzaSyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerLrzaSync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerLrzaSyncResponseObject); ok {
		if err := validResponse.VisitTriggerLrzaSyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMitzSubscription operation middleware
func (sh *strictHandler) CreateMitzSubscription(w http.ResponseWriter, r *http.Request) {
	var request CreateMitzSubscriptionRequestObject

	var body CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMitzSubscription(ctx, request.(CreateMitzSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMitzSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMitzSubscriptionResponseObject); ok {
		if err := validResponse.VisitCreateMitzSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterNVIListBundle operation middleware
func (sh *strictHandler) RegisterNVIListBundle(w http.ResponseWriter, r *http.Request, params RegisterNVIListBundleParams) {
	var request RegisterNVIListBundleRequestObject

	request.Params = params

	var body RegisterNVIListBundleApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterNVIListBundle(ctx, request.(RegisterNVIListBundleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterNVIListBundle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterNVIListBundleResponseObject); ok {
		if err := validResponse.VisitRegisterNVIListBundleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteNVIListsByParams operation middleware
func (sh *strictHandler) DeleteNVIListsByParams(w http.ResponseWriter, r *http.Request, params DeleteNVIListsByParamsParams) {
	var request DeleteNVIListsByParamsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteNVIListsByParams(ctx, request.(DeleteNVIListsByParamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteNVIListsByParams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteNVIListsByParamsResponseObject); ok {
		if err := validResponse.VisitDeleteNVIListsByParamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchNVILists operation middleware
func (sh *strictHandler) SearchNVILists(w http.ResponseWriter, r *http.Request, params SearchNVIListsParams) {
	var request SearchNVIListsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchNVILists(ctx, request.(SearchNVIListsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchNVILists")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchNVIListsResponseObject); ok {
		if err := validResponse.VisitSearchNVIListsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterNVIList operation middleware
func (sh *strictHandler) RegisterNVIList(w http.ResponseWriter, r *http.Request, params RegisterNVIListParams) {
	var request RegisterNVIListRequestObject

	request.Params = params

	var body RegisterNVIListApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterNVIList(ctx, request.(RegisterNVIListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterNVIList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterNVIListResponseObject); ok {
		if err := validResponse.VisitRegisterNVIListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchNVIListsForm operation middleware
func (sh *strictHandler) SearchNVIListsForm(w http.ResponseWriter, r *http.Request, params SearchNVIListsFormParams) {
	var request SearchNVIListsFormRequestObject

	request.Params = params

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body SearchNVIListsFormFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchNVIListsForm(ctx, request.(SearchNVIListsFormRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchNVIListsForm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchNVIListsFormResponseObject); ok {
		if err := validResponse.VisitSearchNVIListsFormResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteNVIList operation middleware
func (sh *strictHandler) DeleteNVIList(w http.ResponseWriter, r *http.Request, id string, params DeleteNVIListParams) {
	var request DeleteNVIListRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteNVIList(ctx, request.(DeleteNVIListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteNVIList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteNVIListResponseObject); ok {
		if err := validResponse.VisitDeleteNVIListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNVIList operation middleware
func (sh *strictHandler) GetNVIList(w http.ResponseWriter, r *http.Request, id string, params GetNVIListParams) {
	var request GetNVIListRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetNVIList(ctx, request.(GetNVIListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNVIList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetNVIListResponseObject); ok {
		if err := validResponse.VisitGetNVIListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EvaluateAuthorizationDirect operation middleware
func (sh *strictHandler) EvaluateAuthorizationDirect(w http.ResponseWriter, r *http.Request) {
	var request EvaluateAuthorizationDirectRequestObject

	var body EvaluateAuthorizationDirectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EvaluateAuthorizationDirect(ctx, request.(EvaluateAuthorizationDirectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EvaluateAuthorizationDirect")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EvaluateAuthorizationDirectResponseObject); ok {
		if err := validResponse.VisitEvaluateAuthorizationDirectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAuthorizationPolicyBundles operation middleware
func (sh *strictHandler) ListAuthorizationPolicyBundles(w http.ResponseWriter, r *http.Request) {
	var request ListAuthorizationPolicyBundlesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuthorizationPolicyBundles(ctx, request.(ListAuthorizationPolicyBundlesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuthorizationPolicyBundles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAuthorizationPolicyBundlesResponseObject); ok {
		if err := validResponse.VisitListAuthorizationPolicyBundlesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthorizationPolicyBundle operation middleware
func (sh *strictHandler) GetAuthorizationPolicyBundle(w http.ResponseWriter, r *http.Request, policyName string) {
	var request GetAuthorizationPolicyBundleRequestObject

	request.PolicyName = policyName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthorizationPolicyBundle(ctx, request.(GetAuthorizationPolicyBundleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthorizationPolicyBundle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthorizationPolicyBundleResponseObject); ok {
		if err := validResponse.VisitGetAuthorizationPolicyBundleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EvaluateAuthorization operation middleware
func (sh *strictHandler) EvaluateAuthorization(w http.ResponseWriter, r *http.Request) {
	var request EvaluateAuthorizationRequestObject

	var body EvaluateAuthorizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EvaluateAuthorization(ctx, request.(EvaluateAuthorizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EvaluateAuthorization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EvaluateAuthorizationResponseObject); ok {
		if err := validResponse.VisitEvaluateAuthorizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request) {
	var request GetStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
