//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	"github.com/zorgbijjou/golang-fhir-models/fhir-models/fhir"
)

// Defines values for PDPAuthzResponsePoliciesReasonsCode.
const (
	Info            PDPAuthzResponsePoliciesReasonsCode = "info"
	InternalError   PDPAuthzResponsePoliciesReasonsCode = "internal_error"
	NotAllowed      PDPAuthzResponsePoliciesReasonsCode = "not_allowed"
	NotImplemented  PDPAuthzResponsePoliciesReasonsCode = "not_implemented"
	PipError        PDPAuthzResponsePoliciesReasonsCode = "pip_error"
	UnexpectedInput PDPAuthzResponsePoliciesReasonsCode = "unexpected_input"
)

// Valid indicates whether the value is a known member of the PDPAuthzResponsePoliciesReasonsCode enum.
func (e PDPAuthzResponsePoliciesReasonsCode) Valid() bool {
	switch e {
	case Info:
		return true
	case InternalError:
		return true
	case NotAllowed:
		return true
	case NotImplemented:
		return true
	case PipError:
		return true
	case UnexpectedInput:
		return true
	default:
		return false
	}
}

// DirectoryUpdateReport Result of one LRZA sync cycle.
//
// Example: {"created":1,"deleted":0,"errors":[],"updated":5,"warnings":["Some-warning-message"]}
type DirectoryUpdateReport struct {
	// Created Number of resources created in the Query Directory.
	//
	// Example: 1
	Created *int `json:"created,omitempty"`

	// Deleted Number of resources deleted from the Query Directory.
	//
	// Example: 0
	Deleted *int `json:"deleted,omitempty"`

	// Errors Fatal issues encountered during the sync.
	//
	// Example: []
	Errors *[]string `json:"errors,omitempty"`

	// Updated Number of resources updated in the Query Directory.
	//
	// Example: 5
	Updated *int `json:"updated,omitempty"`

	// Warnings Non-fatal issues encountered during the sync.
	//
	// Example: ["Some-warning-message"]
	Warnings *[]string `json:"warnings,omitempty"`
}

// FHIRBundle A FHIR R4 Bundle resource. See https://hl7.org/fhir/R4/bundle.html for its schema; not redefined here.
type FHIRBundle = fhir.Bundle

// FHIRList A FHIR R4 List resource (see https://hl7.org/fhir/R4/list.html for its schema; not redefined here). Used here as a pointer: it declares that data of a given category exists for a patient at the custodian organization, without carrying the patient data itself.
//
// Example: {"code":{"coding":[{"code":"MedicationRequest","system":"http://minvws.github.io/generiekefuncties-docs/CodeSystem/nl-gf-data-categories-cs"}]},"extension":[{"url":"http://minvws.github.io/generiekefuncties-docs/StructureDefinition/nl-gf-localization-custodian","valueReference":{"identifier":{"system":"http://fhir.nl/fhir/NamingSystem/ura","value":"00000020"}}}],"mode":"working","resourceType":"List","source":{"identifier":{"system":"http://fhir.nl/fhir/NamingSystem/ura","value":"00000020"}},"status":"current","subject":{"identifier":{"system":"http://fhir.nl/fhir/NamingSystem/bsn","value":"999911136"}}}
type FHIRList = fhir.List

// FHIROperationOutcome A FHIR R4 OperationOutcome resource, returned for error responses. See https://hl7.org/fhir/R4/operationoutcome.html for its schema; not redefined here.
//
// Example: {"issue":[{"code":"value","diagnostics":"missing tenant request header: X-Tenant-ID","severity":"error"}],"resourceType":"OperationOutcome"}
type FHIROperationOutcome = fhir.OperationOutcome

// FHIRSubscription A FHIR R4 Subscription resource. See https://hl7.org/fhir/R4/subscription.html for its schema; not redefined here.
type FHIRSubscription = fhir.Subscription

// PDPAuthzRequest defines model for PDPAuthzRequest.
type PDPAuthzRequest struct {
	Input struct {
		// Context Additional context for the authorization decision, not captured by the `request` object itself.
		Context struct {
			// ConnectionTypeCode Type of connection used for the request. Should be a code from the HL7 EndpointConnectionType code system (http://terminology.hl7.org/CodeSystem/endpoint-connection-type) where applicable.
			//
			//
			// Example: hl7-fhir-rest
			ConnectionTypeCode string `json:"connection_type_code"`

			// DataHolderFacilityType Facility type of the data holder's organization, from the Vektis facility type code system.
			//
			//
			// Example: Z3
			DataHolderFacilityType *string `json:"data_holder_facility_type,omitempty"`

			// DataHolderOrganizationId URA number identifying the data holder's organization.
			//
			// Example: 00000659
			DataHolderOrganizationId string `json:"data_holder_organization_id"`

			// PatientBsn BSN of the patient the request concerns, if already known by the caller. Uses the naming system `http://fhir.nl/fhir/NamingSystem/bsn`.
			//
			//
			// Example: 999911136
			PatientBsn *string `json:"patient_bsn,omitempty"`
		} `json:"context"`

		// Request The HTTP request that is being authorized (e.g. FHIR request).
		Request struct {
			// Body Raw request body. Only read when `Content-Type` is `application/x-www-form-urlencoded`, to extract search or operation parameters; ignored otherwise.
			//
			//
			// Example: identifier=http://fhir.nl/fhir/NamingSystem/bsn|900214181
			Body *string `json:"body,omitempty"`

			// Header HTTP headers of the request being authorized, each value an array of strings. Only `Content-Type` is currently inspected, to detect form-encoded search/operation bodies.
			//
			//
			// Example: {"Content-Type":["application/x-www-form-urlencoded"]}
			Header *map[string][]string `json:"header,omitempty"`

			// Method HTTP method of the request being authorized.
			//
			// Example: GET
			Method string `json:"method"`

			// Path Path of the request. For a FHIR request, this is relative to the FHIR RESTful root (e.g. `/Patient/123`) — it does not include any additional application path prefix such as `/fhir`. Does not include the query string.
			//
			//
			// Example: /Patient/3E439979-017F-40AA-594D-EBCF880FFD97
			Path string `json:"path"`

			// Protocol HTTP protocol version of the request being authorized.
			//
			// Example: HTTP/1.1
			Protocol string `json:"protocol"`

			// Query Raw query string of the request being authorized (e.g. `_since=2024-01-01`), without the leading `?`.
			//
			//
			// Example: _since=2024-01-01
			Query *string `json:"query,omitempty"`
		} `json:"request"`

		// Subject The user and organization on whose behalf the request is being made. Additional unrecognized properties are passed through as-is.
		// In the reference PEP setup, this is sourced directly from the Nuts node's token introspection response (`POST /nuts/auth/v2/accesstoken/introspect`) — no transformation needed.
		Subject PDPAuthzRequest_Input_Subject `json:"subject"`
	} `json:"input"`
}

// PDPAuthzRequest_Input_Subject The user and organization on whose behalf the request is being made. Additional unrecognized properties are passed through as-is.
// In the reference PEP setup, this is sourced directly from the Nuts node's token introspection response (`POST /nuts/auth/v2/accesstoken/introspect`) — no transformation needed.
type PDPAuthzRequest_Input_Subject struct {
	// Active Whether the access token backing this request is currently active.
	//
	// Example: true
	Active *bool `json:"active,omitempty"`

	// ClientId Identifier of the requesting application, e.g. the OAuth2 `client_id` of the client that obtained the access token.
	//
	//
	// Example: gp-portal-client
	ClientId *string `json:"client_id,omitempty"`

	// OrganizationFacilityType Facility type of the requester's organization, from the Vektis facility type code system.
	//
	//
	// Example: Z3
	OrganizationFacilityType *string `json:"organization_facility_type,omitempty"`

	// OrganizationName Display name of the requester's organization.
	//
	// Example: Huisartsenpraktijk Voorbeeld
	OrganizationName *string `json:"organization_name,omitempty"`

	// OrganizationUra URA number identifying the requester's organization.
	//
	// Example: 00000666
	OrganizationUra *string `json:"organization_ura,omitempty"`

	// Scope Space-separated list of OAuth2 scopes, each naming a policy to evaluate (e.g. `bgz`, `mcsd_update`, `pzp_gf`).
	//
	//
	// Example: bgz
	Scope *string `json:"scope,omitempty"`

	// UserId Identifier of the practitioner performing the request (CIBG Dezi-nummer or UZI number).
	//
	//
	// Example: 000095254
	UserId *string `json:"user_id,omitempty"`

	// UserRole Role of the practitioner, from the CIBG Dezi / BIG-register.
	//
	//
	// Example: 01.015
	UserRole             *string                `json:"user_role,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PDPAuthzResponse defines model for PDPAuthzResponse.
type PDPAuthzResponse struct {
	// Allow Overall decision: whether the request being authorized is allowed. This is the only field the PEP is required to honor.
	//
	//
	// Example: true
	Allow *bool `json:"allow,omitempty"`

	// Error Set when the request could not be evaluated (e.g. malformed input).
	//
	// Example: unable to parse FHIR request
	Error *string `json:"error,omitempty"`

	// Policies Per-policy evaluation results, keyed by policy (scope) name. Non-normative: informational, not required to be honored by the PEP.
	Policies *map[string]struct {
		// Allow Whether this specific policy allows the request.
		//
		// Example: true
		Allow *bool `json:"allow,omitempty"`

		// Reasons Explanations for the policy's decision.
		Reasons *[]struct {
			// Code Machine-readable reason code. `info` accompanies an allow; the others accompany a denial or evaluation failure. Implementations may extend this list with additional codes.
			//
			//
			// Example: info
			Code *PDPAuthzResponsePoliciesReasonsCode `json:"code,omitempty"`

			// Description Human-readable explanation of the reason code.
			//
			// Example: MITZ consent granted
			Description *string `json:"description,omitempty"`
		} `json:"reasons,omitempty"`
	} `json:"policies,omitempty"`
}

// PDPAuthzResponsePoliciesReasonsCode Machine-readable reason code. `info` accompanies an allow; the others accompany a denial or evaluation failure. Implementations may extend this list with additional codes.
//
// Example: info
type PDPAuthzResponsePoliciesReasonsCode string

// Count defines model for Count.
type Count = int

// TenantID defines model for TenantID.
type TenantID = string

// OperationOutcomeError A FHIR R4 OperationOutcome resource, returned for error responses. See https://hl7.org/fhir/R4/operationoutcome.html for its schema; not redefined here.
//
// Example: {"issue":[{"code":"value","diagnostics":"missing tenant request header: X-Tenant-ID","severity":"error"}],"resourceType":"OperationOutcome"}
type OperationOutcomeError = FHIROperationOutcome

// RegisterListBundleParams defines parameters for RegisterListBundle.
type RegisterListBundleParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// DeleteListsByParamsParams defines parameters for DeleteListsByParams.
type DeleteListsByParamsParams struct {
	// PatientIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). Mapped to `subject:identifier` before forwarding to NVI.
	PatientIdentifier *string `form:"patient:identifier,omitempty" json:"patient:identifier,omitempty"`

	// SubjectIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). NVI's native parameter name; equivalent to `patient:identifier`.
	SubjectIdentifier *string `form:"subject:identifier,omitempty" json:"subject:identifier,omitempty"`

	// SourceIdentifier Identifier of `List.source` (the system that registered the List), as a FHIR token (`system|value`).
	SourceIdentifier *string `form:"source:identifier,omitempty" json:"source:identifier,omitempty"`

	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// SearchListsParams defines parameters for SearchLists.
type SearchListsParams struct {
	// PatientIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). Mapped to `subject:identifier` before forwarding to NVI.
	PatientIdentifier *string `form:"patient:identifier,omitempty" json:"patient:identifier,omitempty"`

	// SubjectIdentifier BSN of the patient referenced by `List.subject`, as a FHIR token (`system|value`). NVI's native parameter name; equivalent to `patient:identifier`.
	SubjectIdentifier *string `form:"subject:identifier,omitempty" json:"subject:identifier,omitempty"`

	// SourceIdentifier Identifier of `List.source` (the system that registered the List), as a FHIR token (`system|value`).
	SourceIdentifier *string `form:"source:identifier,omitempty" json:"source:identifier,omitempty"`

	// Code `List.code` search parameter, to filter by list/data category (e.g. `MedicationRequest`).
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// UnderscoreCount FHIR `_count` search parameter: maximum number of results per page. Forwarded to NVI as-is.
	UnderscoreCount *Count `form:"_count,omitempty" json:"_count,omitempty"`

	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// RegisterListParams defines parameters for RegisterList.
type RegisterListParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// SearchListsFormFormdataBody defines parameters for SearchListsForm.
type SearchListsFormFormdataBody struct {
	// UnderscoreCount FHIR `_count` search parameter: maximum number of results per page. Forwarded to NVI as-is.
	//
	//
	// Example: 20
	UnderscoreCount   *int    `form:"_count,omitempty" json:"_count,omitempty"`
	Code              *string `form:"code,omitempty" json:"code,omitempty"`
	PatientIdentifier *string `form:"patient:identifier,omitempty" json:"patient:identifier,omitempty"`
	SourceIdentifier  *string `form:"source:identifier,omitempty" json:"source:identifier,omitempty"`
	SubjectIdentifier *string `form:"subject:identifier,omitempty" json:"subject:identifier,omitempty"`
}

// SearchListsFormParams defines parameters for SearchListsForm.
type SearchListsFormParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// DeleteListParams defines parameters for DeleteList.
type DeleteListParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// GetListParams defines parameters for GetList.
type GetListParams struct {
	// XTenantID The local care organization, who is performing (or on whose behalf) the request is being made, as a FHIR token: `<system>|<value>` where `<system>` must be `http://fhir.nl/fhir/NamingSystem/ura`.
	XTenantID TenantID `json:"X-Tenant-ID"`
}

// CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody defines body for CreateMitzSubscription for application/fhir+json ContentType.
type CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody = FHIRSubscription

// RegisterListBundleApplicationFhirPlusJSONRequestBody defines body for RegisterListBundle for application/fhir+json ContentType.
type RegisterListBundleApplicationFhirPlusJSONRequestBody = FHIRBundle

// RegisterListApplicationFhirPlusJSONRequestBody defines body for RegisterList for application/fhir+json ContentType.
type RegisterListApplicationFhirPlusJSONRequestBody = FHIRList

// SearchListsFormFormdataRequestBody defines body for SearchListsForm for application/x-www-form-urlencoded ContentType.
type SearchListsFormFormdataRequestBody SearchListsFormFormdataBody

// EvaluateAuthorizationJSONRequestBody defines body for EvaluateAuthorization for application/json ContentType.
type EvaluateAuthorizationJSONRequestBody = PDPAuthzRequest

// Getter for additional properties for PDPAuthzRequest_Input_Subject. Returns the specified
// element and whether it was found
func (a PDPAuthzRequest_Input_Subject) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PDPAuthzRequest_Input_Subject
func (a *PDPAuthzRequest_Input_Subject) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PDPAuthzRequest_Input_Subject to handle AdditionalProperties
func (a *PDPAuthzRequest_Input_Subject) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["active"]; found {
		err = json.Unmarshal(raw, &a.Active)
		if err != nil {
			return fmt.Errorf("error reading 'active': %w", err)
		}
		delete(object, "active")
	}

	if raw, found := object["client_id"]; found {
		err = json.Unmarshal(raw, &a.ClientId)
		if err != nil {
			return fmt.Errorf("error reading 'client_id': %w", err)
		}
		delete(object, "client_id")
	}

	if raw, found := object["organization_facility_type"]; found {
		err = json.Unmarshal(raw, &a.OrganizationFacilityType)
		if err != nil {
			return fmt.Errorf("error reading 'organization_facility_type': %w", err)
		}
		delete(object, "organization_facility_type")
	}

	if raw, found := object["organization_name"]; found {
		err = json.Unmarshal(raw, &a.OrganizationName)
		if err != nil {
			return fmt.Errorf("error reading 'organization_name': %w", err)
		}
		delete(object, "organization_name")
	}

	if raw, found := object["organization_ura"]; found {
		err = json.Unmarshal(raw, &a.OrganizationUra)
		if err != nil {
			return fmt.Errorf("error reading 'organization_ura': %w", err)
		}
		delete(object, "organization_ura")
	}

	if raw, found := object["scope"]; found {
		err = json.Unmarshal(raw, &a.Scope)
		if err != nil {
			return fmt.Errorf("error reading 'scope': %w", err)
		}
		delete(object, "scope")
	}

	if raw, found := object["user_id"]; found {
		err = json.Unmarshal(raw, &a.UserId)
		if err != nil {
			return fmt.Errorf("error reading 'user_id': %w", err)
		}
		delete(object, "user_id")
	}

	if raw, found := object["user_role"]; found {
		err = json.Unmarshal(raw, &a.UserRole)
		if err != nil {
			return fmt.Errorf("error reading 'user_role': %w", err)
		}
		delete(object, "user_role")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PDPAuthzRequest_Input_Subject to handle AdditionalProperties
func (a PDPAuthzRequest_Input_Subject) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Active != nil {
		object["active"], err = json.Marshal(a.Active)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'active': %w", err)
		}
	}

	if a.ClientId != nil {
		object["client_id"], err = json.Marshal(a.ClientId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'client_id': %w", err)
		}
	}

	if a.OrganizationFacilityType != nil {
		object["organization_facility_type"], err = json.Marshal(a.OrganizationFacilityType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'organization_facility_type': %w", err)
		}
	}

	if a.OrganizationName != nil {
		object["organization_name"], err = json.Marshal(a.OrganizationName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'organization_name': %w", err)
		}
	}

	if a.OrganizationUra != nil {
		object["organization_ura"], err = json.Marshal(a.OrganizationUra)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'organization_ura': %w", err)
		}
	}

	if a.Scope != nil {
		object["scope"], err = json.Marshal(a.Scope)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scope': %w", err)
		}
	}

	if a.UserId != nil {
		object["user_id"], err = json.Marshal(a.UserId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'user_id': %w", err)
		}
	}

	if a.UserRole != nil {
		object["user_role"], err = json.Marshal(a.UserRole)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'user_role': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// TriggerLrzaSync Trigger LRZA synchronization
	// (POST /lrza/update)
	TriggerLrzaSync(w http.ResponseWriter, r *http.Request)
	// CreateMitzSubscription Create a MITZ consent subscription
	// (POST /mitz/Subscription)
	CreateMitzSubscription(w http.ResponseWriter, r *http.Request)
	// RegisterListBundle Register a List via a transaction Bundle
	// (POST /nvi)
	RegisterListBundle(w http.ResponseWriter, r *http.Request, params RegisterListBundleParams)
	// DeleteListsByParams Delete Lists matching search parameters
	// (DELETE /nvi/List)
	DeleteListsByParams(w http.ResponseWriter, r *http.Request, params DeleteListsByParamsParams)
	// SearchLists Search for Lists
	// (GET /nvi/List)
	SearchLists(w http.ResponseWriter, r *http.Request, params SearchListsParams)
	// RegisterList Register a List directly
	// (POST /nvi/List)
	RegisterList(w http.ResponseWriter, r *http.Request, params RegisterListParams)
	// SearchListsForm Search for Lists (form-encoded body)
	// (POST /nvi/List/_search)
	SearchListsForm(w http.ResponseWriter, r *http.Request, params SearchListsFormParams)
	// DeleteList Delete a List by ID
	// (DELETE /nvi/List/{id})
	DeleteList(w http.ResponseWriter, r *http.Request, id string, params DeleteListParams)
	// GetList Read a List by ID
	// (GET /nvi/List/{id})
	GetList(w http.ResponseWriter, r *http.Request, id string, params GetListParams)
	// ListPolicyBundles List loaded policy bundles
	// (GET /pdp/bundles)
	ListPolicyBundles(w http.ResponseWriter, r *http.Request)
	// GetPolicyBundle Get a loaded policy bundle by name
	// (GET /pdp/bundles/{policyName})
	GetPolicyBundle(w http.ResponseWriter, r *http.Request, policyName string)
	// EvaluateAuthorization Evaluate an authorization request
	// (POST /pdp/v1/data/knooppunt/authz)
	EvaluateAuthorization(w http.ResponseWriter, r *http.Request)
	// GetStatus Readiness check
	// (GET /status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// GetVersion Build version info
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// TriggerLrzaSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerLrzaSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerLrzaSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMitzSubscription operation middleware
func (siw *ServerInterfaceWrapper) CreateMitzSubscription(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMitzSubscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterListBundle operation middleware
func (siw *ServerInterfaceWrapper) RegisterListBundle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterListBundleParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterListBundle(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteListsByParams operation middleware
func (siw *ServerInterfaceWrapper) DeleteListsByParams(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteListsByParamsParams

	// ------------- Optional query parameter "patient:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "patient:identifier", r.URL.Query(), &params.PatientIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "patient:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "patient:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "subject:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject:identifier", r.URL.Query(), &params.SubjectIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "subject:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source:identifier", r.URL.Query(), &params.SourceIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source:identifier", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteListsByParams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchLists operation middleware
func (siw *ServerInterfaceWrapper) SearchLists(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchListsParams

	// ------------- Optional query parameter "patient:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "patient:identifier", r.URL.Query(), &params.PatientIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "patient:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "patient:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "subject:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "subject:identifier", r.URL.Query(), &params.SubjectIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "subject:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source:identifier" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source:identifier", r.URL.Query(), &params.SourceIdentifier, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source:identifier"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source:identifier", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "_count" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "_count", r.URL.Query(), &params.UnderscoreCount, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "_count"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "_count", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchLists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterList operation middleware
func (siw *ServerInterfaceWrapper) RegisterList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterListParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchListsForm operation middleware
func (siw *ServerInterfaceWrapper) SearchListsForm(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchListsFormParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchListsForm(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteList operation middleware
func (siw *ServerInterfaceWrapper) DeleteList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteListParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteList(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-ID")]; found {
		var XTenantID TenantID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-ID", valueList[0], &XTenantID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-ID", Err: err})
			return
		}

		params.XTenantID = XTenantID

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetList(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPolicyBundles operation middleware
func (siw *ServerInterfaceWrapper) ListPolicyBundles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPolicyBundles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPolicyBundle operation middleware
func (siw *ServerInterfaceWrapper) GetPolicyBundle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "policyName" -------------
	var policyName string

	err = runtime.BindStyledParameterWithOptions("simple", "policyName", r.PathValue("policyName"), &policyName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "policyName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPolicyBundle(w, r, policyName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EvaluateAuthorization operation middleware
func (siw *ServerInterfaceWrapper) EvaluateAuthorization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EvaluateAuthorization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/lrza/update", wrapper.TriggerLrzaSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/pdp/v1/data/knooppunt/authz", wrapper.EvaluateAuthorization)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pdp/bundles", wrapper.ListPolicyBundles)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/pdp/bundles/{policyName}", wrapper.GetPolicyBundle)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/nvi", wrapper.RegisterListBundle)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/nvi/List", wrapper.DeleteListsByParams)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/nvi/List", wrapper.SearchLists)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/nvi/List", wrapper.RegisterList)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/nvi/List/_search", wrapper.SearchListsForm)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/nvi/List/{id}", wrapper.DeleteList)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/nvi/List/{id}", wrapper.GetList)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/mitz/Subscription", wrapper.CreateMitzSubscription)

	return m
}

type OperationOutcomeErrorApplicationFhirPlusJSONResponse FHIROperationOutcome

type TriggerLrzaSyncRequestObject struct {
}

type TriggerLrzaSyncResponseObject interface {
	VisitTriggerLrzaSyncResponse(w http.ResponseWriter) error
}

type TriggerLrzaSync200JSONResponse DirectoryUpdateReport

func (response TriggerLrzaSync200JSONResponse) VisitTriggerLrzaSyncResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type TriggerLrzaSync500TextResponse string

func (response TriggerLrzaSync500TextResponse) VisitTriggerLrzaSyncResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type CreateMitzSubscriptionRequestObject struct {
	Body *CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody
}

type CreateMitzSubscriptionResponseObject interface {
	VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error
}

type CreateMitzSubscription201ApplicationFhirPlusJSONResponse FHIRSubscription

func (response CreateMitzSubscription201ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMitzSubscription400ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response CreateMitzSubscription400ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMitzSubscription500ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response CreateMitzSubscription500ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMitzSubscription503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response CreateMitzSubscription503ApplicationFhirPlusJSONResponse) VisitCreateMitzSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterListBundleRequestObject struct {
	Params RegisterListBundleParams
	Body   *RegisterListBundleApplicationFhirPlusJSONRequestBody
}

type RegisterListBundleResponseObject interface {
	VisitRegisterListBundleResponse(w http.ResponseWriter) error
}

type RegisterListBundle200ApplicationFhirPlusJSONResponse FHIRBundle

func (response RegisterListBundle200ApplicationFhirPlusJSONResponse) VisitRegisterListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterListBundle400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response RegisterListBundle400ApplicationFhirPlusJSONResponse) VisitRegisterListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterListBundle500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterListBundle500ApplicationFhirPlusJSONResponse) VisitRegisterListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterListBundle503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterListBundle503ApplicationFhirPlusJSONResponse) VisitRegisterListBundleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteListsByParamsRequestObject struct {
	Params DeleteListsByParamsParams
}

type DeleteListsByParamsResponseObject interface {
	VisitDeleteListsByParamsResponse(w http.ResponseWriter) error
}

type DeleteListsByParams204Response struct {
}

func (response DeleteListsByParams204Response) VisitDeleteListsByParamsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteListsByParams400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response DeleteListsByParams400ApplicationFhirPlusJSONResponse) VisitDeleteListsByParamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteListsByParams500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteListsByParams500ApplicationFhirPlusJSONResponse) VisitDeleteListsByParamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteListsByParams503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteListsByParams503ApplicationFhirPlusJSONResponse) VisitDeleteListsByParamsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SearchListsRequestObject struct {
	Params SearchListsParams
}

type SearchListsResponseObject interface {
	VisitSearchListsResponse(w http.ResponseWriter) error
}

type SearchLists200ApplicationFhirPlusJSONResponse FHIRBundle

func (response SearchLists200ApplicationFhirPlusJSONResponse) VisitSearchListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchLists400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response SearchLists400ApplicationFhirPlusJSONResponse) VisitSearchListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchLists422ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchLists422ApplicationFhirPlusJSONResponse) VisitSearchListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SearchLists500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchLists500ApplicationFhirPlusJSONResponse) VisitSearchListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchLists503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchLists503ApplicationFhirPlusJSONResponse) VisitSearchListsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterListRequestObject struct {
	Params RegisterListParams
	Body   *RegisterListApplicationFhirPlusJSONRequestBody
}

type RegisterListResponseObject interface {
	VisitRegisterListResponse(w http.ResponseWriter) error
}

type RegisterList200ApplicationFhirPlusJSONResponse FHIRList

func (response RegisterList200ApplicationFhirPlusJSONResponse) VisitRegisterListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterList400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response RegisterList400ApplicationFhirPlusJSONResponse) VisitRegisterListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterList500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterList500ApplicationFhirPlusJSONResponse) VisitRegisterListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterList503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response RegisterList503ApplicationFhirPlusJSONResponse) VisitRegisterListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SearchListsFormRequestObject struct {
	Params SearchListsFormParams
	Body   *SearchListsFormFormdataRequestBody
}

type SearchListsFormResponseObject interface {
	VisitSearchListsFormResponse(w http.ResponseWriter) error
}

type SearchListsForm200ApplicationFhirPlusJSONResponse FHIRBundle

func (response SearchListsForm200ApplicationFhirPlusJSONResponse) VisitSearchListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchListsForm400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response SearchListsForm400ApplicationFhirPlusJSONResponse) VisitSearchListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchListsForm422ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchListsForm422ApplicationFhirPlusJSONResponse) VisitSearchListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SearchListsForm500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchListsForm500ApplicationFhirPlusJSONResponse) VisitSearchListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SearchListsForm503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response SearchListsForm503ApplicationFhirPlusJSONResponse) VisitSearchListsFormResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteListRequestObject struct {
	Id     string `json:"id"`
	Params DeleteListParams
}

type DeleteListResponseObject interface {
	VisitDeleteListResponse(w http.ResponseWriter) error
}

type DeleteList204Response struct {
}

func (response DeleteList204Response) VisitDeleteListResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteList400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response DeleteList400ApplicationFhirPlusJSONResponse) VisitDeleteListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteList500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteList500ApplicationFhirPlusJSONResponse) VisitDeleteListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteList503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response DeleteList503ApplicationFhirPlusJSONResponse) VisitDeleteListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetListRequestObject struct {
	Id     string `json:"id"`
	Params GetListParams
}

type GetListResponseObject interface {
	VisitGetListResponse(w http.ResponseWriter) error
}

type GetList200ApplicationFhirPlusJSONResponse FHIRList

func (response GetList200ApplicationFhirPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetList400ApplicationFhirPlusJSONResponse struct {
	OperationOutcomeErrorApplicationFhirPlusJSONResponse
}

func (response GetList400ApplicationFhirPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetList500ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response GetList500ApplicationFhirPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetList503ApplicationFhirPlusJSONResponse FHIROperationOutcome

func (response GetList503ApplicationFhirPlusJSONResponse) VisitGetListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/fhir+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListPolicyBundlesRequestObject struct {
}

type ListPolicyBundlesResponseObject interface {
	VisitListPolicyBundlesResponse(w http.ResponseWriter) error
}

type ListPolicyBundles200JSONResponse []string

func (response ListPolicyBundles200JSONResponse) VisitListPolicyBundlesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPolicyBundleRequestObject struct {
	PolicyName string `json:"policyName"`
}

type GetPolicyBundleResponseObject interface {
	VisitGetPolicyBundleResponse(w http.ResponseWriter) error
}

type GetPolicyBundle200Response struct {
}

func (response GetPolicyBundle200Response) VisitGetPolicyBundleResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type GetPolicyBundle404Response struct {
}

func (response GetPolicyBundle404Response) VisitGetPolicyBundleResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type EvaluateAuthorizationRequestObject struct {
	Body *EvaluateAuthorizationJSONRequestBody
}

type EvaluateAuthorizationResponseObject interface {
	VisitEvaluateAuthorizationResponse(w http.ResponseWriter) error
}

type EvaluateAuthorization200JSONResponse PDPAuthzResponse

func (response EvaluateAuthorization200JSONResponse) VisitEvaluateAuthorizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type EvaluateAuthorization400JSONResponse PDPAuthzResponse

func (response EvaluateAuthorization400JSONResponse) VisitEvaluateAuthorizationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatusRequestObject struct {
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus200TextResponse string

func (response GetStatus200TextResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetStatus503TextResponse string

func (response GetStatus503TextResponse) VisitGetStatusResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(503)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetVersionRequestObject struct {
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200TextResponse string

func (response GetVersion200TextResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// TriggerLrzaSync Trigger LRZA synchronization
	// (POST /lrza/update)
	TriggerLrzaSync(ctx context.Context, request TriggerLrzaSyncRequestObject) (TriggerLrzaSyncResponseObject, error)
	// CreateMitzSubscription Create a MITZ consent subscription
	// (POST /mitz/Subscription)
	CreateMitzSubscription(ctx context.Context, request CreateMitzSubscriptionRequestObject) (CreateMitzSubscriptionResponseObject, error)
	// RegisterListBundle Register a List via a transaction Bundle
	// (POST /nvi)
	RegisterListBundle(ctx context.Context, request RegisterListBundleRequestObject) (RegisterListBundleResponseObject, error)
	// DeleteListsByParams Delete Lists matching search parameters
	// (DELETE /nvi/List)
	DeleteListsByParams(ctx context.Context, request DeleteListsByParamsRequestObject) (DeleteListsByParamsResponseObject, error)
	// SearchLists Search for Lists
	// (GET /nvi/List)
	SearchLists(ctx context.Context, request SearchListsRequestObject) (SearchListsResponseObject, error)
	// RegisterList Register a List directly
	// (POST /nvi/List)
	RegisterList(ctx context.Context, request RegisterListRequestObject) (RegisterListResponseObject, error)
	// SearchListsForm Search for Lists (form-encoded body)
	// (POST /nvi/List/_search)
	SearchListsForm(ctx context.Context, request SearchListsFormRequestObject) (SearchListsFormResponseObject, error)
	// DeleteList Delete a List by ID
	// (DELETE /nvi/List/{id})
	DeleteList(ctx context.Context, request DeleteListRequestObject) (DeleteListResponseObject, error)
	// GetList Read a List by ID
	// (GET /nvi/List/{id})
	GetList(ctx context.Context, request GetListRequestObject) (GetListResponseObject, error)
	// ListPolicyBundles List loaded policy bundles
	// (GET /pdp/bundles)
	ListPolicyBundles(ctx context.Context, request ListPolicyBundlesRequestObject) (ListPolicyBundlesResponseObject, error)
	// GetPolicyBundle Get a loaded policy bundle by name
	// (GET /pdp/bundles/{policyName})
	GetPolicyBundle(ctx context.Context, request GetPolicyBundleRequestObject) (GetPolicyBundleResponseObject, error)
	// EvaluateAuthorization Evaluate an authorization request
	// (POST /pdp/v1/data/knooppunt/authz)
	EvaluateAuthorization(ctx context.Context, request EvaluateAuthorizationRequestObject) (EvaluateAuthorizationResponseObject, error)
	// GetStatus Readiness check
	// (GET /status)
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// GetVersion Build version info
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// TriggerLrzaSync operation middleware
func (sh *strictHandler) TriggerLrzaSync(w http.ResponseWriter, r *http.Request) {
	var request TriggerLrzaSyncRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerLrzaSync(ctx, request.(TriggerLrzaSyncRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerLrzaSync")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerLrzaSyncResponseObject); ok {
		if err := validResponse.VisitTriggerLrzaSyncResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMitzSubscription operation middleware
func (sh *strictHandler) CreateMitzSubscription(w http.ResponseWriter, r *http.Request) {
	var request CreateMitzSubscriptionRequestObject

	var body CreateMitzSubscriptionApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMitzSubscription(ctx, request.(CreateMitzSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMitzSubscription")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMitzSubscriptionResponseObject); ok {
		if err := validResponse.VisitCreateMitzSubscriptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterListBundle operation middleware
func (sh *strictHandler) RegisterListBundle(w http.ResponseWriter, r *http.Request, params RegisterListBundleParams) {
	var request RegisterListBundleRequestObject

	request.Params = params

	var body RegisterListBundleApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterListBundle(ctx, request.(RegisterListBundleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterListBundle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterListBundleResponseObject); ok {
		if err := validResponse.VisitRegisterListBundleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteListsByParams operation middleware
func (sh *strictHandler) DeleteListsByParams(w http.ResponseWriter, r *http.Request, params DeleteListsByParamsParams) {
	var request DeleteListsByParamsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteListsByParams(ctx, request.(DeleteListsByParamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteListsByParams")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteListsByParamsResponseObject); ok {
		if err := validResponse.VisitDeleteListsByParamsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchLists operation middleware
func (sh *strictHandler) SearchLists(w http.ResponseWriter, r *http.Request, params SearchListsParams) {
	var request SearchListsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchLists(ctx, request.(SearchListsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchLists")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchListsResponseObject); ok {
		if err := validResponse.VisitSearchListsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterList operation middleware
func (sh *strictHandler) RegisterList(w http.ResponseWriter, r *http.Request, params RegisterListParams) {
	var request RegisterListRequestObject

	request.Params = params

	var body RegisterListApplicationFhirPlusJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterList(ctx, request.(RegisterListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterListResponseObject); ok {
		if err := validResponse.VisitRegisterListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchListsForm operation middleware
func (sh *strictHandler) SearchListsForm(w http.ResponseWriter, r *http.Request, params SearchListsFormParams) {
	var request SearchListsFormRequestObject

	request.Params = params

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body SearchListsFormFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchListsForm(ctx, request.(SearchListsFormRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchListsForm")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchListsFormResponseObject); ok {
		if err := validResponse.VisitSearchListsFormResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteList operation middleware
func (sh *strictHandler) DeleteList(w http.ResponseWriter, r *http.Request, id string, params DeleteListParams) {
	var request DeleteListRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteList(ctx, request.(DeleteListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteListResponseObject); ok {
		if err := validResponse.VisitDeleteListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetList operation middleware
func (sh *strictHandler) GetList(w http.ResponseWriter, r *http.Request, id string, params GetListParams) {
	var request GetListRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetList(ctx, request.(GetListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetListResponseObject); ok {
		if err := validResponse.VisitGetListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPolicyBundles operation middleware
func (sh *strictHandler) ListPolicyBundles(w http.ResponseWriter, r *http.Request) {
	var request ListPolicyBundlesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPolicyBundles(ctx, request.(ListPolicyBundlesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPolicyBundles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPolicyBundlesResponseObject); ok {
		if err := validResponse.VisitListPolicyBundlesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPolicyBundle operation middleware
func (sh *strictHandler) GetPolicyBundle(w http.ResponseWriter, r *http.Request, policyName string) {
	var request GetPolicyBundleRequestObject

	request.PolicyName = policyName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPolicyBundle(ctx, request.(GetPolicyBundleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPolicyBundle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPolicyBundleResponseObject); ok {
		if err := validResponse.VisitGetPolicyBundleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// EvaluateAuthorization operation middleware
func (sh *strictHandler) EvaluateAuthorization(w http.ResponseWriter, r *http.Request) {
	var request EvaluateAuthorizationRequestObject

	var body EvaluateAuthorizationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.EvaluateAuthorization(ctx, request.(EvaluateAuthorizationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "EvaluateAuthorization")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(EvaluateAuthorizationResponseObject); ok {
		if err := validResponse.VisitEvaluateAuthorizationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request) {
	var request GetStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request) {
	var request GetVersionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
