name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.4']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: |
          go.sum
          test/testdata/go.sum

    - name: Download dependencies
      run: go mod download

    - name: Run Go tests
      run: go test -p 1 -v ./...

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: pep/nginx/js/package-lock.json

    - name: Install PEP test dependencies
      run: npm ci
      working-directory: pep/nginx/js

    - name: Run PEP tests
      run: npm test
      working-directory: pep/nginx/js